### ISSUE TITLE
Issue running rspec

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#1]
I can't get rsmp validator running. Running rspec gives the following error message:

Failure/Error: require 'rsmp'

Errno::ENOENT:
  No such file or directory @ realpath_rec - /var/lib/gems/2.5.0/gems/rsmp-0.1.0/lib/rsmp_schema

**Comment by otterdahl** [comment]
Found the isssue. The following patch fixed it:
```
diff --git a/Gemfile.lock b/Gemfile.lock
index 6bdf1c5..ce187d8 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -20,7 +20,7 @@ GEM
       uri_template (~> 0.7)
     nio4r (2.5.2)
     regexp_parser (1.6.0)
-    rsmp (0.1.0)
+    rsmp (0.1.2)
       async (~> 1.23.0)
       async-io (~> 1.27.0)
       colorize (~> 0.8.1)
```

**Comment by emiltin** [comment]
This should be fixed in the Gemfile:

```
gem 'rsmp', '~> 0.1.2'
```

**Comment by emiltin** [comment]
fixed in master
