### ISSUE TITLE
ITC3 workflow: Add activate/deactivate alarm scripts

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#111]
The scripts from ITC2 can be reused. However, they need access to the terminal interface which is available on serial connection (RS232) in a real controller or TCP/IP in the simulator. We need to figure out which method we can use

**Comment by emiltin** [comment]
mov to other repo?

**Comment by otterdahl** [comment]
ITC3 alarms can be triggered using "Force Input." See https://github.com/rsmp-nordic/rsmp_validator/issues/161
