### ISSUE TITLE
ITC3 workflow: Adjust the ITC-3 configuration to allow testing of alarms

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#112]

**Comment by emiltin** [comment]
move to other repo?

**Comment by otterdahl** [comment]
The ITC-3 configuration has been updated, but the alarm test cases needs to be updated in order to trigger alarms using RSMP itself. See https://github.com/rsmp-nordic/rsmp_validator/issues/161
