### ISSUE TITLE
Links in documentation doesn't work

### ISSUE THREAD

**Issue by Rodgulgronademonen** [rsmp-nordic/rsmp_validator#113]
Many of the links result in "page not found". See e.g. links under RSMP Validator "About".

**Comment by emiltin** [comment]
Thanks for reporting this. They all work locally. Problem is that that subpath rsmp_validator/ must be added on github pages.

**Comment by emiltin** [comment]
fixed. all links should now work.

note that internal links (links that point to pages on the the rsmp validator website are checked when buildind the site, and therefore there should not be any broken links. but they can still link to the wrong page of course. external links (to other domains) are not checked when building the site.
