### ISSUE TITLE
Requests during startup sequence

### ISSUE THREAD

**Issue by alexanderzapf** [rsmp-nordic/rsmp_validator#126]
Hello,

I have a question regarding the spec/site/core/aggregated_status_spec.rc (also other tests have that issue)

Our site is connecting and initiates the startup-sequence as expected, but after sending the watchdog the test sends the AggregatedStatusRequest, which our site answers with NotAck as we don't allow requests or commands being sent during startup.

According to the test it seems that requests/commands should be allowed during startup-sequence, is that true?
Or is the startup sequence considered finished after Ack'ing the supervision site's version?

**Comment by emiltin** [comment]
Hi @alexanderzapf thank you for opening this issue. See https://github.com/rsmp-nordic/rsmp_core/issues/34.
When the connection sequence is considered complete is not entirely clear in the current core spec, but we plan to clarify it in the upcoming version.
When do you current implementation consider the connection sequence to be complete?

**Comment by alexanderzapf** [comment]
Okay, I see, thank you. Currently we consider it done after sending the AggregatedStatus. We should change it then to either after Version or initial Watchdog till it is clarified.

**Comment by emiltin** [comment]
The validator (which acts as a supervisor) currently considers the sequence complete after it the Version message it sends has been acknowledged.

**Comment by emiltin** [comment]
closing, please open new issue if you have additional questions
