### ISSUE TITLE
change test for invalid security code - don't expect NotAck

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#132]
the corrrect behaviour when receiving a command with an incorrect security code is to send a command response with values set to the current states. the site should not respond with a  NotAck.

**Comment by otterdahl** [comment]
This behaviour has changed since SXL 1.1. Now we do expect NotAck, See https://github.com/rsmp-nordic/rsmp_core/issues/79

**Comment by emiltin** [comment]
The test in quesiton is "security code is rejected when incorrect".
I suppose the test should behave differently depending on the sxl version then? If sxl >= 1.1 then we should expect a NotAc (as we currently do) but from 1.0.7 to 1.0.15 it should expect a command response with values set to the current states.

This old behaviour also needs to be implemented in the gem tcl emulator.

**Comment by otterdahl** [comment]
> The test in quesiton is "security code is rejected when incorrect". I suppose the test should behave differently depending on the sxl version then? 

Correct

**Comment by emiltin** [comment]
related to https://github.com/rsmp-nordic/rsmp_validator/issues/134

**Comment by otterdahl** [comment]
> Looking a fixing this. But why is the behaviour regarding how an invalid security code is rejected defined in the SXL and not Core? I would think that the behaviour should be the same for alle types of equipment?

Because it's part of the SXL and only exists in the SXL for TLC's.

**Comment by emiltin** [comment]
fixed with #327. we not only test behaviour when sending incorrect security codes for tlc sxl>=1.1. for earlier versions, the behaviour is (yet) undefined.
