### ISSUE TITLE
disable  emergency routes using index

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#137]
it's not very clear in the spec, but it seems that each active emergency route must be disabled using index.

just sending status=False with no index is undefined behaviour.

https://github.com/rsmp-nordic/rsmp_validator/blob/8ef33e425cdbf4b7d73ea4fd6029c74ba6a04bfb/spec/support/command_helpers.rb#L136

**Comment by emiltin** [comment]
@otterdahl?

**Comment by otterdahl** [comment]
In general, all commands needs all arguments and this is command is no exception. There is many cases where commands make no sense unless all arguments are included.

I don't remember if this is already stated as a requirement elsewhere or if it is an open issue in core.

**Comment by otterdahl** [comment]
This issue was fixed  with df02505b572ee6f36563437d13f268b8a88f3bb0

**Comment by otterdahl** [comment]
Opened PR https://github.com/rsmp-nordic/rsmp_validator/pull/252 for a missing check in the response
