### ISSUE TITLE
tlc emulator should switch groups to A or B when fixed time 

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#145]
fixing an issue with test passing even though status collection failled, exposed this issue.

the tlc emulator fails the test 'fixed time activation should cause all groups to go to state A or B'.

what's expected behaviour? How long should groups stay in A or B, and what happens afterwards?

**Comment by otterdahl** [comment]
I don't understand that test case and I don't remember the discussion behind it. Why would "fixed time" cause all groups to go to state A or B? 🤷

**Comment by emiltin** [comment]
no idea...

**Comment by emiltin** [comment]
remove it outright?

**Comment by otterdahl** [comment]
Yes. Remove it. There must have been some misunderstanding behind it.
