### ISSUE TITLE
Add alarm tests for ITC-3

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#161]
Configuration changes in the ITC-3 programming has been made. It is possible to trigger alarms in the ITC-3.

- Force input 152 to enable detector error (always on)
- Force input 153 to enable detector error (always off)
- Force input 154 to enable conflict error
- Force input 155 to enable red l1 error
- Force input 156 to enable red l2 error

Unforcing them should remove the error.

This means that is is possible to trigger alarms using RSMP. No need to run an external script.
The alarm test cases needs to be updated in order to perform these steps.

**Comment by emiltin** [comment]
done
