### ISSUE TITLE
ITC-3: M0001 related tests fail

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#168]
Any tests that check that uses M0001 'NormalControl' fails with ITC-3. This is because there it checks S0007 (Switched on) to be "True". But the ITC-3 always reports "False".

This is because the TLC is running in "Off" mode because there is no lamps connected to the TLC. Trying to set the TLC in "On" mode causes serious errors, due to no lamp load.

Either lamps needs to be connected to the TLC, or the alarms needs to suppressed using an updated configuration of the TLC.

**Comment by emiltin** [comment]
how can the 'off' mode be read with rsmp?

**Comment by otterdahl** [comment]
> how can the 'off' mode be read with rsmp?

Using S0007 (switched on)

**Comment by otterdahl** [comment]
Trying to run ITC-3 in simulation mode (SIMUL) does not help

**Comment by otterdahl** [comment]
> Any tests that check that uses M0001 'NormalControl' fails with ITC-3. This is because there it checks S0007 (Switched on) to be "True". But the ITC-3 always reports "False".
> 
> This is because the TLC is running in "Off" mode because there is no lamps connected to the TLC. Trying to set the TLC in "On" mode causes serious errors, due to no lamp load.
> 
> Either lamps needs to be connected to the TLC, or the alarms needs to suppressed using an updated configuration of the TLC.

This problem is cirumvented by setting the TLC into simulation mode

**Comment by otterdahl** [comment]
Another issue:

The M0001 contains the argument "timeout", but rsmp_validator doesn't seem to include it?
Checkout: 
https://github.com/rsmp-nordic/rsmp_validator/runs/5600067104?check_suite_focus=true#step:5:42

But it exists in the test case:
https://github.com/rsmp-nordic/rsmp_validator/blob/fcb90710ba7878ebbd811bfe925eaba61d06c264/spec/support/command_helpers.rb#L92

Any thoughts @emiltin?

**Comment by emiltin** [comment]
It was because the method `switch_yellow_flash()` used `nil` as default argument value for timeout, and this was then passed on to  `set_functional_position()`.

Fixed with 826133d in the m0001_itc3 branch. the ITC-3 now passes the M0001 test in that branch.

**Comment by emiltin** [comment]
fixed with #183
