### ISSUE TITLE
Spec 3.1.5 - StatusSubscribe: sendOnChange (sOc) flag is missing 

### ISSUE THREAD

**Issue by melihercan** [rsmp-nordic/rsmp_validator#175]
During `detector_logics_spec.rb` tests, I realize that  `sendOnChange (sOc)` flag is missing in the arguments of `StatusSubscribe` message. 

Here is the message from validator:
 `f8ea  Sent StatusSubscribe  {"mType":"rSMsg","type":"StatusSubscribe","ntsOId":"","xNId":"","cId":"TC","sS":[{"sCI":"S0002","n":"detectorlogicstatus","uRt":"0"}],"mId":"f8ea59cc-94bc-4b2c-bba5-e784764227fc"}`

I checked and couldn't find if  `sendOnChange (sOc)` is an optional element. Therefore, I think this flag should be specified in the message after `uRt`.

**Comment by emiltin** [comment]
hi, thanks for flagging this. you rigth that the validator should use new the sendOnChange attribute, which was adddd in core 3.1.5

**Comment by emiltin** [comment]
Should be fixed with #230 and #240. Can you confirm it's works for you in master?

**Comment by melihercan** [comment]
Yes, I will test it and report here at my earliest convenience.

**Comment by emiltin** [comment]
> Yes, I will test it and report here at my earliest convenience.

did you get a chance to test this?
