### ISSUE TITLE
Reintroduce workflow_dispatch in workflows?

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#178]
I've noticed that workflow_dispatch were removed back in commit aaf89f85f0c94d9f49aa420766ddccffc294fa1b. workflow_dispatch  makes it possible to manually trigger a workflow to be run. I've kind of miss this since the physical TLC's sometimes may change internal configuration and it would be useful to manually trigger the tests to see if the updates changes the outcome without needing to push anything to the repo.

**Comment by emiltin** [comment]
I see, feel free put them back in.

**Comment by otterdahl** [comment]
Done
