### ISSUE TITLE
Clarification of M0019 'status' element and its usage in 'io_spec.rb' tests

### ISSUE THREAD

**Issue by melihercan** [rsmp-nordic/rsmp_validator#180]
In the document, `status` is defined as:
```
Name:
status 

Command:
setInput

Type:
boolean

Value:
-False
-True  

Comment:
False: Force input  
True: Release input
```

First of all, the purpose of this element is not very clear to me. I believe some more explanation is  required. What is `Release input`?

Then its usage in `io_spec.rb` tests is even more confusing. Below I provided parts from the test log:
```
> Force input 5 to False
{"M0019"=>{"setInput"=>{"securityCode"=>"2222", "status"=>"True", "input"=>"5", "inputValue"=>"False"}}}
> Wait for input 5 to be forced
Waiting for StatusUpdate/StatusResponse matching {"S0029"=>{"status"=>/^.{4}1/}}
> Wait for input 5 to be False
Waiting for StatusUpdate/StatusResponse matching {"S0003"=>{"inputstatus"=>/^.{4}0/}}
```
If we are forcing, according to the doc "status" should be "False"!!! According to the test, forcing means "status" should be "True"!

Further in the tests
``` 
> Force input 5 to True
{"M0019"=>{"setInput"=>{"securityCode"=>"2222", "status"=>"True", "input"=>"5", "inputValue"=>"True"}}}
> Wait for input 5 to be forced
Waiting for StatusUpdate/StatusResponse matching {"S0029"=>{"status"=>/^.{4}1/}}
> Wait for input 5 to be to True
Waiting for StatusUpdate/StatusResponse matching {"S0003"=>{"inputstatus"=>/^.{4}1/}}
```
For this step:
```
> Wait for input 5 to be forced
Waiting for StatusUpdate/StatusResponse matching {"S0029"=>{"status"=>/^.{4}1/}}
```
If I return status with the expected value `"status"=>/^.{4}1/`, I get NACK! saying that no change detected and that is contradictory:
```
2022-04-14T06:03:13.887Z  56589  SignageClient        DL1                  c766  Rejected StatusUpdate message, no change for S0029 'status'  {"mType":"rSMsg","type":"StatusUpdate","mId":"c766e2b1-4d1f-46e8-b5f6-435a062ce3e6","ntsOId":"","xNId":"","cId":"DL1","sTs":"2022-04-14T06:03:13.858Z","sS":[{"sCI":"S0029","n":"status","s":"00001","q":"recent"}]}
    2022-04-14T06:03:13.890Z  56589  SignageClient        -                    -     Sent MessageNotAck for StatusUpdate c766  {"mType":"rSMsg","type":"MessageNotAck","rea":"no change for S0029 'status'","oMId":"c766e2b1-4d1f-46e8-b5f6-435a062ce3e6"}

Sentinel warning: RSMP::RepeatedStatusError: Rejected StatusUpdate message,no change for S0029 'status' {"mType":"rSMsg","type":"StatusUpdate","mId":"c766e2b1-4d1f-46e8-b5f6-435a062ce3e6","ntsOId":"","xNId":"","cId":"DL1","sTs":"2022-04-14T06:03:13.858Z","sS":[{"sCI":"S0029","n":"status","s":"00001","q":"recent"}]}
```

I am confused and any help is appreciated.

**Comment by otterdahl** [comment]
> First of all, the purpose of this element is not very clear to me. I believe some more explanation is required. What is `Release input`?

It means that the given input (1-255) should no longer be forced to True or False.

> Then its usage in `io_spec.rb` tests is even more confusing. Below I provided parts from the test log:
> 
> ```
> > Force input 5 to False
> {"M0019"=>{"setInput"=>{"securityCode"=>"2222", "status"=>"True", "input"=>"5", "inputValue"=>"False"}}}
> > Wait for input 5 to be forced
> Waiting for StatusUpdate/StatusResponse matching {"S0029"=>{"status"=>/^.{4}1/}}
> > Wait for input 5 to be False
> Waiting for StatusUpdate/StatusResponse matching {"S0003"=>{"inputstatus"=>/^.{4}0/}}
> ```
> 
> If we are forcing, according to the doc "status" should be "False"!!! According to the test, forcing means "status" should be "True"!

Correct. This is a typo in the SXL. This is fixed in the upcoming version 1.1. The test case reflects the next version of the SXL.

**Comment by emiltin** [comment]
btw, are you testing a TLC implementation? M0019 is part of the SXL for TLCs. I don't think any other equipment has defined a M0019 command.

**Comment by melihercan** [comment]
> btw, are you testing a TLC implementation? M0019 is part of the SXL for TLCs. I don't think any other equipment has defined a M0019 command.

Yes I am testing a TLC implementation.

**Comment by emiltin** [comment]
hi @melihercan i think this issue can be closed?

**Comment by melihercan** [comment]
> hi @melihercan i think this issue can be closed?

Hi @emiltin yes I am closing it. Thanks...
