### ISSUE TITLE
S0024: are values with 3 digits allowed?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#188]
The test "Site::Traffic Light Controller Signal Plan offset is read with S0024" fails in ITC-3, because the the following value of s "1-255,2-0,3-0,4-0,5-0,6-0,7-0,8-0,9-0" includes numbers that use thee digits.

The specs at https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/sxl_traffic_light_controller.html#s0024, indicate that you must two digits, and the examples at https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/sxl_traffic_light_controller.html#s0024 and use two digits.

The schema validation follows this requirement, which is why the number 255 is rejected.

Should numbers with 1, 2 or 3 or any number of digits be allowed?
Are you required to use leading zeros e.g 05 if you send 5? That seems cumbersome.

I would prefer to first change the spec to show p-t,p-t and write that numbers must be integers from 0-255. However, the min/max cannot be easily verified using json schema, as long as we're using these convoluted string types. So later I think we should move to native json types, in this case an array of arrays, like: [[255,2],[0,3],[0,4]].

**Comment by emiltin** [comment]
@otterdahl do you have input?

**Comment by otterdahl** [comment]
I think numbers with 1, 2 or 3 or any number should be allowed, (e.g 0-255)

There is also no point requiring leading zeros e.g 05.

**Comment by emiltin** [comment]
> I think numbers with 1, 2 or 3 or any number should be allowed, (e.g 0-255)
> 
> There is also no point requiring leading zeros e.g 05.

I agree. We should just provide a min and a max, and describe the format with `p-t,p-t`, like in S0026.
Since the spec is not that clear I think we can also change the current schema to allow 3 digits. Unfortunately, the custom comma separated list format does not allow us to validate min/max values, but we can check that there is no more that 3 digits, so in effect 0-999 will be allowed by the schema.

**Comment by emiltin** [comment]
PR in the schema repo: https://github.com/rsmp-nordic/rsmp_schema/pull/71

**Comment by emiltin** [comment]
The change in the scheme has been included in the tlc sxl 1.1, and in the rsmp gem, and finally in the validator.
The corresponding ITC-3 should therefore not fail anymore. Let's check after the next nightly test run.

**Comment by emiltin** [comment]
ITC-3 offline?
