### ISSUE TITLE
ITC-3 fails because S0006 sets emergencystage to empty string

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#189]
According to the spec at https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/sxl_traffic_light_controller.html#s0006, the S0006 attribute 'emergencystage' must be set to an integer in the range 1-255, but the ITC-3 sends an empty string:

2022-08-08T13:21:03.117Z  51680  KK+AG9998=001TC000   KK+AG9998=001TC000   0314  Received invalid StatusUpdate, schema errors: /sS/1/s, pattern, schema errors: /sS/1/s, pattern,  {"mType":"rSMsg","type":"StatusUpdate","mId":"031463b3-6399-4281-88f8-6c640e72d15d","ntsOId":"KK+AG9998=001TC000","xNId":"","cId":"KK+AG9998=001TC000","sTs":"2022-08-08T13:21:02.837Z","sS":[{"sCI":"S0006","n":"status","s":"False","q":"recent"},{"sCI":"S0006","n":"emergencystage","s":"","q":"recent"}]}

**Comment by SwarcoPalm** [comment]
What value would you propose if there is no emergency logic configured in the controller?

**Comment by otterdahl** [comment]
Good question. My suggestion is to use "0" if there is no emergency logic defined in the controller.

**Comment by emiltin** [comment]
This needs to be clarified in the documentation. There's already a discussion about it at https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/issues/110#issuecomment-972868514.

For now I suggest modifiying the json schema to allow emergencystate=null when status=False.

**Comment by emiltin** [comment]
My conclusion here is that we allow state that emergencystage should be set to zero when no route is active. When a route is being decativeated, you should of course set emergencystage to the route being deactivated. The schema reflects this - emergencystage must be an integer (as a string). So no changes are needed in the validator, as I see it. But equipment must pass zero when no route is active, not an empty string.

**Comment by sveitech** [comment]
I am a bit confused by the latest reply:

Quote:
- emergencystage should be set to zero when no route is active.
- When a route is being decativeated, you should of course set emergencystage to the route being deactivated.

These two statements are conflicting, unless you differentiate between "no route is active" and "deactivated" states.

**Comment by emiltin** [comment]
I think supporting multiple routes acticated at the same time is problematic with S0006. You can send several message, but that would conflict with how status responses are normally send.

If we limit S0006 to one active route, then my understanding would be:

- when a route is activated => send S0006 with routenr and status=True
- when a route is deactivated => send S0006 with routenr and status=False
- when status is requested or send due to update rate and route is active => send S0006 with routenr and status=True
- when status is requested or send due to update rate and no route is active => send S0006 with routenr=0 and status=False

I have not heard or a need to know about routes being somehow in progress/transition.

**Comment by emiltin** [comment]
Superseded by #270
