### ISSUE TITLE
Alarm test doesn't fail due to schema errors

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#19]
The alarm tests should fail when there is schema errors.

How do we make the tests fail in these situations?

**Comment by emiltin** [comment]
You can expect a block of code to raise a particular error:
https://relishapp.com/rspec/rspec-expectations/v/2-11/docs/built-in-matchers/raise-error-matcher

**Comment by emiltin** [comment]
fixed
