### ISSUE TITLE
Swarco TLC uses 'q' instead of 'ageState' for core version 3.1.2

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#197]
In status messages, the field 'ageState' was renamed 'q' in core version 3.1.3.

The Swarco TLCs implement core 3.1.2, but incorrectly uses 'q'. It should use 'ageState'.

```
2022-09-23T10:41:47.656Z  60964  KK+AG9998=001TC000   -                    -     Connection to site KK+AG9998=001TC000 established, using core 3.1.2, tlc 1.0.7
...
2022-09-23T10:44:00.692Z  50254  KK+AG9998=001TC000   KK+AG9998=001TC000   6568  Received invalid StatusResponse, schema errors: /sS/0, required, {"missing_keys"=>["ageState"]}, /sS/0/q, schema, , /sS/1, required, {"missing_keys"=>["ageState"]}, /sS/1/q, schema, , /sS/2, required, {"missing_keys"=>["ageState"]}, /sS/2/q, schema, , /sS/3, required, {"missing_keys"=>["ageState"]}, /sS/3/q, schema, , /sS/4, required, {"missing_keys"=>["ageState"]}, /sS/4/q, schema, , /sS/5, required, {"missing_keys"=>["ageState"]}, /sS/5/q, schema,  {"mType":"rSMsg","type":"StatusResponse","mId":"65686858-720c-4f6e-8b63-5cf36b63ce60","ntsOId":"KK+AG9998=001TC000","xNId":"","cId":"KK+AG9998=001TC000","sTs":"2022-09-23T10:44:00.637Z","sS":[{"sCI":"S0096","n":"year","s":"2022","q":"recent"},{"sCI":"S0096","n":"month","s":"9","q":"recent"},{"sCI":"S0096","n":"day","s":"23","q":"recent"},{"sCI":"S0096","n":"hour","s":"10","q":"recent"},{"sCI":"S0096","n":"minute","s":"44","q":"recent"},{"sCI":"S0096","n":"second","s":"0","q":"recent"}]}
```

**Comment by emiltin** [comment]
Both ITC-2 and ITC-3

**Comment by otterdahl** [comment]
> ping @otterdahl do you agree that 'q' is not valid until core v 3.1.3?

Yes. I agree. It makes me think whether they really implement 3.1.2 or a later version.

I know that it is possible to set the specific RSMP version in the config file of the TLC's. Perhaps they are reporting the wrong version?

**Comment by emiltin** [comment]
Maybe @SwarcoPalm can answer?

**Comment by SwarcoPalm** [comment]
3.1.2 specifies "q:" for status response, per section 5.5.5.2 in Riktlinje RSMP_Kommunikationsprotokoll_vägsidesutrustning_3_1_2.pdf (see attached screenshot)


![image](https://user-images.githubusercontent.com/19303587/193799615-23f03404-3087-4efa-8618-647375ecef6d.png)

**Comment by SwarcoPalm** [comment]
Command responses are shown as "age:" in the documentation. The ITC behaves according to these 2 sections

![image](https://user-images.githubusercontent.com/19303587/193800203-47b3c8e8-b142-4ec8-9b62-2400b8cb2e55.png)

**Comment by SwarcoPalm** [comment]
in any case, "ageState" I think has never been a valid name in the JSON serialisation of RSMP

**Comment by SwarcoPalm** [comment]
This is the same in 3.1.3 by the way

**Comment by emiltin** [comment]
Thank you Anders.

For the StatusResponse the XML uses ageState, while the JSON uses q.
For the CommandResponse, the XML uses ageState, while the JSON uses age.

I suspect this inconsistency is an error in the documentation, but David can probably shed light on this.

Has XML ever been used anywhere?

**Comment by otterdahl** [comment]
> I suspect this inconsistency is an error in the documentation, but David can probably shed light on this.

I agree this is a bit inconsistent. I think this a mistake, but I don't know if it worth changing now. 

> Has XML ever been used anywhere?

Yes. It was used in VMS signs with RSMP 1.0.

To speed up the process of writing the RSMP spec 3.0, the spec was mostly unchanged with the exeption of a new chapter containing XML-JSON comparison.

**Comment by emiltin** [comment]
OK. 

1) Should we allow both q and ageState in the schema for 3.1.2? I think we need to.

2) Is q or ageState preferred for 3.1.2, e.g. which one should the rsmp gem use when sending data in 3.1.2? Since equipment and MobiMaestro uses ageState for 3.1.2, perhaps that's what the gem should use too.

3) Is the document Anders posted still in use? It must be clear what the correct way to implement 3.1.2 is, and what documentation is authoritative. The 3.1.2 core spec at https://rsmp-nordic.org/rsmp_specifications/core/3.1.2/index.html uses ageState consistently, as far as I can tell.

**Comment by SwarcoPalm** [comment]
I think 

1) "ageState" should never be used. It's not mentioned at all in the JSON serialisation. It must be "q:" or "age:" in my opinion. I know that the name of the field is ageState.

2) I would suggest to use "q" and "age:" but to allow them to be interchanged as the documentation is unclear on this.

3) The core spec at the link also does not use ageState in any shown JSON serialisation, see attached screenshot

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/19303587/194052938-dc0e9981-4ff3-48a9-bd08-50d36187f3ff.png">

**Comment by otterdahl** [comment]
> 1) Should we allow both q and ageState in the schema for 3.1.2? I think we need to.

Only "q" should be used, since we're using JSON. Using "ageState" is only for XML, which is not used since RSMP 1.0

In [section 4.2](https://rsmp-nordic.org/rsmp_specifications/core/3.1.2/applicability/object_model.html)
it states: "In section **Basic structure** all examples is provided in XML
format for clarity. But the communication between the facility and
supervision systems / other facility uses JSON format. In section **Usage
of JSON** all message types in both XML and JSON are provided side by
side."

**Comment by emiltin** [comment]
alright, i'll change the gem and rsmp schema to use q instead of ageState.

**Comment by emiltin** [comment]
The changelog for the core spec includes this for 3.1.3:

 - "ageState" changed name to "q" (quality)

https://github.com/rsmp-nordic/rsmp_core/blob/master/ChangeLog.md#version-313

Which is why i originally uses q in the schema from 3.1.3. But it seems this is wrong, and was changed from 3.1.2?


I find it unfortunate that different names are used for XML and JSON serialization.

**Comment by otterdahl** [comment]
>  - "ageState" changed name to "q" (quality)
> 
> https://github.com/rsmp-nordic/rsmp_core/blob/master/ChangeLog.md#version-313
> 
> Which is why i originally uses q in the schema from 3.1.3. But it seems this is wrong, and was changed from 3.1.2?

I understand. I believe "ageState" was a typo somewhere in the 3.1.2 spec, however I agree that this is not clear in the changelog.

**Comment by otterdahl** [comment]
> The core spec here on GitHub includes tag no older that 3.1.2, although the changelog goes back to 0.92. What's the oldest version we should support in the json schema and gem? 3.1.2?

I don't think we need to support older versions than 3.1.2. I don't
think older versions than 3.1.2 are used anywhere.

**Comment by emiltin** [comment]
the rsmp_schema and rsmp gem - and thus the validator - has been update use use q instead of ageStage. core 3.1.2 is now the oldest support version.
