### ISSUE TITLE
Docker container for easy installation

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#200]
For people familiar with Docker, providing a container with the validator installed could make installation eaiser.

If we choose to provide a container, it should be auto-build using a github action.

**Comment by otterdahl** [comment]
A PR has been created at https://github.com/rsmp-nordic/rsmp_validator/pull/208, which adds a Dockerfile

Building docker images and pushing them is possible, but [requires a paid subscription on Docker hub](https://docs.docker.com/docker-hub/builds/). Investigate GitHub Container Registry instead?

**Comment by otterdahl** [comment]
I've added workflows to both [rsmp_validator](https://github.com/rsmp-nordic/rsmp_validator) and [rsmp](https://github.com/rsmp-nordic/rsmp) repositories which builds docker images and publishes them to [Packges](https://github.com/orgs/rsmp-nordic/packages). It triggers when pushing to the `docker` branch.

**Comment by otterdahl** [comment]
The docker PR has been merged.
