### ISSUE TITLE
Can't seem to connect to supervisor on Linux

### ISSUE THREAD

**Issue by DavidAdamsBluecity** [rsmp-nordic/rsmp_validator#205]
I've been trying various settings, but I can't seem to get the Validator to connect when running either test suite on Ubuntu 20.04.

It connects when using the RSMP ruby gem by itself, but it times out when using the Validator. I've made sure the ports match in the configs. Is there something I'm overlooking?

**Comment by otterdahl** [comment]
- Make sure that `config/validator.yaml` exists. There is a sample config in `config/validator_example.yaml`
- Make sure that `site: config/gem_tlc.yaml` is set properly in `config/validator.yaml` (the default is `site: config/gem_site.yaml`)
- Make sure `port: 12111` is set correctly in `config/gem_tlc.yaml` (the default in this file is `port: 13111`)

You may also adjust the following timeout in `config/gem_tlc.yaml` to e.g. 60
```yaml
timeouts:
  connect: 60
```
If it still doesn't connect, please make sure the validator listens to the correct port.
For instance:
```bash
$ ss -l -4 | grep 12111
tcp   LISTEN 0      4096          0.0.0.0:12111            0.0.0.0:*
```

**Comment by DavidAdamsBluecity** [comment]
Thanks. It looks as though everything's properly configured, and I've confirmed that the validator is listening to the correct port, but it's still timing out.

There must be some other error occurring.

**Comment by otterdahl** [comment]
Another thing...

Please make sure you start the rsmp executable this way:
in `rsmp/`
```bash
$ bundle exec rsmp site
```
and then...
in `rsmp_validator/`
```bash
$ bundle exec rspec spec/site
```

**Comment by DavidAdamsBluecity** [comment]
Thanks, I also tried that. With supervisors too. It still times out. Something must be unable to communicate, but only in the validator code.

**Comment by DavidAdamsBluecity** [comment]
Thanks, I did get it working eventually and forgot to close the issue. I can't remember what the fix was, but I'm pretty sure it was a user error, either in the config or in the installation. I'll close it now.

**Comment by emiltin** [comment]
Great to hear you got it working.
