### ISSUE TITLE
subscribe test eg S0001 must adhere to the core RSMP version specs (3.1.2, 3.1.5)

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#210]
The subscription test of S0001 uses the latest RSMP core protocol version implicitly (3.1.5.). This version of the subscription datagram adds a "sOc" field, breaking tests of all previous core versions.

**Comment by sveitech** [comment]
#209 is the same issue. Consider closing 209 in favor of this one.

**Comment by emiltin** [comment]
hi @sveitech, does PR #230 solve the issue for you?
