### ISSUE TITLE
RSMP 3.1.5 specific StatusSubscribe element "sOc" is hardcoded, without regard for chosen core_version

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#211]
subscribe_spec.rb uses "s0c" field.
command_helpers.rb, function verify_startup_sequence uses "sOc" field.
status_helpers.rb, function wait_for_status uses "sOc" field.

This field should only be used when the selected core_version is >= 3.1.5.

**Comment by emiltin** [comment]
same as #210?

**Comment by emiltin** [comment]
fixed
