### ISSUE TITLE
refactor status_spec.rb file

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#22]
the file is geting too long.

many of the tests do nothing more than verify that a response is received. it then verifies the format of the response, but can be removed, this the format is already verified by the JSON schema. we just need to make sure any patterns matching is also in the schema.

tests that just verifies that a respons is received are very similar and could be refactored to use a commend helper method, reducing the amount of code.

of course we might also think of way to do additional verification, specific to each status.

**Comment by otterdahl** [comment]
True. Many of the tests only verfies that the response is recieved. This is different from the **command_spec.rb** where each command typically is verified against a status. The level of supported statuses differs much between the manufacturers.

**Comment by emiltin** [comment]
Patterns matching of comma separated lists are not working as intended. Eg.```/^True|False(,True|False)*$/``` matches anything starting with "True", like True,xxx", but does not match ""False,False". But as mentioned I suggest moving these regex patterns to the schema and remove from the ruby test file.

**Comment by emiltin** [comment]
I suggest we reorganize test files according to functionality instead of status/command/alarm. Testing commands will typically involve requesting statuses, etc. So we could organize by e.g. signal plan, inputs, etc instead, and then use commands, statuses, alarms, etc. as needed to test that specific functionality.

**Comment by otterdahl** [comment]
OK. And while reorganizing, also differentiate generic RSMP tests to the specific TLC tests

**Comment by emiltin** [comment]
factoring out common functionality to helpers has been implemented

**Comment by emiltin** [comment]
done
