### ISSUE TITLE
alarm_spec.rb does not respect RSMP core version (always uses 3.1.5 spec)

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#221]
The alarm tests uses RSMP core 3.1.5 features as hardcoded values.

For example, the alarm state "inActive" is used, but for RSMP core 3.1.2, this should be "inactive".

This seems to be a recurring issue throughout the test cases. Either the tester should indicate that it can only test the current version of the RSMP spec, or the tests should respect the restrict_testing: core_version: field from the yaml config.

**Comment by emiltin** [comment]
First step will be to fix this case-by-case by changing behaviour depending on the version used when testing, as determined by the connection handshake. This can be read from site.sxl_version and site.core_version.

Later I would like to introduce a site proxy object with high-level methods for interacting with a remote site, which abstract these version details away.

**Comment by emiltin** [comment]
- [x] sOc in status requests
- [ ] inactive or inActive in alarm status

**Comment by emiltin** [comment]
The alarm tests check that the aS attribute match the regex `/inActive/i`. The `i` at the end means that the match is done case-insensitively, so it will match both inactive and inActive.

**Comment by emiltin** [comment]
PR #255 introduces string case match in alarm tests from core 3.2

**Comment by emiltin** [comment]
@sveitech did you find anythin else hardcoded in the alarm test? otherwise i think we can close this issue

**Comment by emiltin** [comment]
done. @sveitech you're welcome to open a new issue if you find anything else that needs to be changed
