### ISSUE TITLE
signal_groups_spec.rb: "follow startup sequence after yellow flash" fragile due to its specificity

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#224]
This test checks if the controller can move through all 3 startup intervals. This requires a very specific controller configuration, and seems odd to include in a generalized RSMP testing setup. This is testing the controller itself, rather than the reporting functionality of RSMP.

An ITC controller may be configured to skip one or more startup intervals.

Suggest to keep the RSMP validator to test actual RSMP specifications, and not controller operational specifications. I. E. It would seem odd to also test that yellow follows green, and red follows red in the group state tests.

**Comment by emiltin** [comment]
same question for: signal_groups_spec.rb: "follows startup sequence after restart" fragile test, so closed issue #225

**Comment by emiltin** [comment]
I believe we do want functional tests, as long as they are configurable enough. Since the expected startup sequence is configurable, I think we can close this issue? @otterdahl?

What I can do is tag these test with `:functional` so it's easy to exclude them (or run only these) if you like.

**Comment by otterdahl** [comment]
I think functional tests are very useful and it's a great oportunity for us as a road authority to use the validator to check compliance.

This specific test case is based on the Swedish requirement for how TLC's must start. Specfied in Transportstyrelsens författningssamling [TSFS](https://www.transportstyrelsen.se/TSFS/TSFS%202014_30k.pdf), chapter 2, §17 (page 4)

The signal group status should begin with this sequence:

- Start-up interval 1: minimum 3 seconds, yellow flash for vehicles and bicycles
- Start-up interval 2: minimum 3 seconds, yellow
- Start-up interval 3: minimum 3 seconds, red

But this may be different in Denmark and other countries. So it needs to be configurable both regarding the sequence and duration. Adding the tag `:functional` is useful.

I think we can close this issue.

**Comment by sveitech** [comment]
I think it is scope creep. this is an RSMP validator, not a traffic light controller validator. The validator is complex enough to run as it is with all the custom setup that is required. This just adds further complexity on top.

The more functional tests you add to the validator, the more responsibility you put on yourself to supply proper configuration files for the individual traffic controllers (not just the json config files but the actual traffic controller configurations).

Considering how long we have already spent on properly configuring an ITC unit to comply with these tests, further complexity will not make it easier for the next party to repeat this setup.

Sure, a generalized traffic controller tester would be nice, but this is not the place to do so. The validator is becoming more and more specialized to the traffic controllers that you know of. Consider the additional issues you have opened (#277, #278). The RSMP specification does not state what controller specific alarms should be mapped to RSMP alarms. And neither should it. it is an over-specification.

**Comment by emiltin** [comment]
this is also discussed in #18
