### ISSUE TITLE
command_helpers.rb, traffic_situations_spec.rb: Command M0003 is missing "status" field.

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#226]
```
 # Set traffic situation
  def set_traffic_situation ts
    require_security_codes
    command_list = build_command_list :M0003, :setTrafficSituation, {
      securityCode: Validator.config['secrets']['security_codes'][2],
      traficsituation: ts   # misspell 'traficsituation'is in the rsmp spec

    }
    send_command_and_confirm @task, command_list, "Switch to traffic situation #{ts}"
  end
```

The command is missing the "status" field which indicates if the controller should choose situation automatically. The SXL does not state that this field is optional.

**Comment by emiltin** [comment]
I agree, docs at https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.0.15/sxl_traffic_light_controller.html#m0003 indicate that the status field is required.

@otterdahl do you agree?

This should be fixed first in the rsmp schema: https://github.com/rsmp-nordic/rsmp_schema/issues/29

**Comment by otterdahl** [comment]
Yes. I agree.
Same as https://github.com/rsmp-nordic/rsmp_validator/issues/219

**Comment by emiltin** [comment]
ok. closing this duplicate in favour of #219

**Comment by emiltin** [comment]
hi @sveitech, our ITC-2 has no traffic situations configured, and our ITC-3 is offline. I hope we can get it fixed, but in the meantime, perhaps you can see if latest master fixed the issue for you (missing status attribute when testing M0003).

**Comment by sveitech** [comment]
The issue has been resolved in latest version. Thank you.

**Comment by emiltin** [comment]
Great, thanks for checking.
