### ISSUE TITLE
S0024: Maximum 2 digits for time offset

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#227]
The validator fails when S0024 reads a time-offset greater than 99.

The specification is ambiguous. The format is "pp-tt". Either it should specify what the range limits are (00-99) or it should be relaxed to allow arbitrary integer numbers, as long as they are separated by a "-". The ITC device supports up to 255 seconds of offset.

**Comment by emiltin** [comment]
since the spec states the forma tis pp-tt, i think this is a spec issue, so moving to https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/issues/159
