### ISSUE TITLE
Add docker documentation on website

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#229]
Here is step-by-step instructions to getting started using docker. They need to be added to the web page, but I`m unsure how to it properly.

Step-by-step:

1. Create a new folder for storing configuration files. Place it somewhere convenient. It serves the same purpose as the `config/` folder [as described here](https://rsmp-nordic.org/rsmp_validator/config/).
2. This folder needs at least a [validator.conf](https://rsmp-nordic.org/rsmp_validator/config/#choosing-what-config-to-use) and the actual configuration file for the TLC or simulator. Here is an [example for the gem simulator](https://github.com/rsmp-nordic/rsmp_validator/blob/master/config/gem_tlc.yaml).
3. Download and install  docker, for instance [Docker Desktop](https://www.docker.com/products/docker-desktop).
4. Open a command prompt and run `docker pull ghcr.io/rsmp-nordic/rsmp_validator:docker`. You can find the [available docker images on github](https://github.com/rsmp-nordic/rsmp_validator/pkgs/container/rsmp_validator).
5. If you're using Docker Desktop, find `rsmp_validator` in the images tab and press `Run`
6. Select *Optional settings*. Use the following settings:
   * Ports: `12111` 
   * Volumes:
      * Host path: *Select the folder you created in step 1*
      * Container Path: `/config`
7. Start the validator by starting the container.

By default the container will run `bundle exec rspec spec/site`.

If you want to use custom command line options you can start the container like this example:
`docker container run -it --name rsmp_validator -v C:/Users/rsmp/Desktop/config:/config -p 12111:12111 rsmp_validator --format Validator::Brief --tag '~script' spec/site/tlc/detector_logics_spec.rb:31`

**Comment by emiltin** [comment]
See the file docs/internal/doc_flow.md. Essentially, the docs is a Jekyll site, and you write pages as Markdow places in docs/. Once you push to the docs branch (or master), the site is rebuild and pushed to the branch gh-pages, which causes the public website to update at https://rsmp-nordic.org/rsmp_validator/.

**Comment by emiltin** [comment]
So if you make a PR against docs, you can see the result on https://rsmp-nordic.org/rsmp_validator/ as soon as a the GitHub action has run and GitHub pages have updated. If you like what you see, you can merge to master.

Ideally we would have a staging server where we coud view changes before actually making them public.

**Comment by emiltin** [comment]
I'm creating a PR for this. 

But I notice that it mentions that it will by default run `bundle exec rspec spec/site`. This should to be changed to a specific equipment type, e.g. spec/site/tlc. At the moment we only have tests for the TLC, but once we add other types, it will not make sense to run tests for different types.

**Comment by otterdahl** [comment]
> But I notice that it mentions that it will by default run `bundle exec rspec spec/site`. This should to be changed to a specific equipment type, e.g. spec/site/tlc. At the moment we only have tests for the TLC, but once we add other types, it will not make sense to run tests for different types.

The default that the validator will run is determined by the CMD directive in the Dockerfile. We can update this if needed, but it is easy to override this as described in the doc.

```Dockerfile
CMD [ "spec/site" ]
```

> The validator.conf you mention - I suppose you mean validator.yaml?

Right

**Comment by emiltin** [comment]
PR and discussion is now in #246
