### ISSUE TITLE
command tests shoud use TestSite.connected when possible

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#25]
isolated() will disconnect and reconnect, which will make running tests a lot slower. connected() should be used where possible. isolated() is meant for situations where you need to ensure that you've just connected.

**Comment by otterdahl** [comment]
Yes. I remember that I had issues with connected() at some point. Possibly using M0004 but it could have been with somewhere else too. We can replace isolated() with connected() and re-run the tests with the TLC's to see if it fails for some tests or not.

**Comment by emiltin** [comment]
ok let's try that

**Comment by emiltin** [comment]
if changed it for all command tests, except M0004 (restart). Is it working with the swarco emulator?

**Comment by otterdahl** [comment]
I don't think M0004 can be tested with the software-only emulator. It needs to be tested with real hardware.

**Comment by emiltin** [comment]
OK.
The Ruby TLC emulator supports M0004. It sends a command response, then closes and reopens the connection. But it doesn't yet move all groups to red first, neither does it have a real start-up sequence.

**Comment by emiltin** [comment]
Most tests not just connected(). open new issues if something is not working
