### ISSUE TITLE
Branch for running equipment tests? 

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#251]
It's a bit annoying to see all our checks fail all the time, because equipment either fails some tests, or are offline. Very often, we're fixing things and running just the Gem TLC tests and the various docker and doc build actions is enough.

Maybe it would be better to run equipment tests (Swarco and Dynniq) only when pushing to a specific branch like `equipment`. Or we can run them only when we actually update the master branch, instead of on a PR.

Another possibility is to schedule them to run e.g. once per day.

**Comment by otterdahl** [comment]
I'm in favour of creating a specific branch for equipment tests. We have no ETA when they can be up and running again.

**Comment by emiltin** [comment]
Equipment tests now run when on pull requests against the branch `equipemnt`.

In addition, euqipment tests run daily at 3:45AM UTC (using the `schedule` trigger).

You can easily insert badged in markdown, showing the latest status af workflows, eg:

[![Gem TLC](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/gem_tlc.yml/badge.svg)](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/gem_tlc.yml)
[![Dynniq EC-2](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/dynniq_ec2.yml/badge.svg)](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/dynniq_ec2.yml)
[![Swarco ITC-2](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/swarco_itc2.yml/badge.svg)](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/swarco_itc2.yml)
[![Swarco ITC-3](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/swarco_itc3.yml/badge.svg)](https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/swarco_itc3.yml)

Should we place them somewhere, e.g. on the RSMP website, or on the readme here on github?

**Comment by emiltin** [comment]
done

**Comment by otterdahl** [comment]
> Should we place them somewhere, e.g. on the RSMP website, or on the readme here on github?

I think it is a great idea to place them on the RSMP website and on github too.

This is something I know people has been asking for a long time. It is generally hard to know what equipment actually supports RSMP. Right now several manufacturers claim RSMP compatibility, but it hasn't been verified by us.

**Comment by emiltin** [comment]
OK, i'll start by placing them here in the github repo. Regarding the website, we might need a page dedicated to our test ghub and results?

**Comment by otterdahl** [comment]
yeah, that would be a good idea
