### ISSUE TITLE
ITC-3 Custom error messages not mapped to RSMP Alarm

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#277]
There is a possibility to create custom error messages in ITC-3. They show up as alarms in the controller, but are not sent using RSMP. They should map as A0009 (other error). A0009 used for [other errors not covered by any other alarm type.](https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/sxl_traffic_light_controller.html#a0009)

**Comment by sveitech** [comment]
Please report controller specific bugs or issues on our company portal. We do not track or monitor this repository for issues related to our implementation of the RSMP protocol.

**Comment by emiltin** [comment]
Do you have a link to that portal? Different road authorities have contracts with different service providers.

I assume you want to deliver a product without known issues, so I recommend that you follow this repo to get first-hand insight into the bugs we find and how they can be reproduced.

**Comment by SwarcoPalm** [comment]
They are now mapped in the latest RSMP release on ITC-3 and I believe the issue can be closed

**Comment by emiltin** [comment]
I do see some A0009 alarms received by the validator.
