### ISSUE TITLE
ITC-3 Watchdog timeouts

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#289]
How is the watchdog interval configured on the ITC-3? The validator sometimes closes the connection because no watchdog was received within 120s.

```
    2021-09-10T21:32:39.720Z 34152    KK+AG9998=001TC000       No Watchdog within 120 seconds
```

Perhaps  disconnects should be stored as sentinel errors, so they are shown as part of the test result

**Comment by SwarcoPalm** [comment]
I'm just reviewing open issues and I believe this can be closed?

**Comment by emiltin** [comment]
It's not a problem for recent core version, but I don't know about earlier core version; at the moment the ITC -3 connected to the test hub is only tested for 3.2.0. But we know have the ability to test on a range of core version. Should we enable this?

**Comment by SwarcoPalm** [comment]
Sure go ahead. The validator also validated this for 3.1.5 before the switch to 3.2.0.

The implementation of RSMP in ITC-3 is a complete rewrite since the issue was opened 3 years ago, so I believe it can be closed :)

**Comment by emiltin** [comment]
OK, I've added ITC-3 testing for core version 3.1.2 - 3.2.0. You can see a run at https://github.com/rsmp-nordic/rsmp_validator/actions/runs/10808667811/job/29982139513?pr=434.
