### ISSUE TITLE
sends Watchdog too early with core 3.1.2

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#291]
It sends the first Watchdog before the initial supervisor Version message has been acknowledged.

```
  Failure/Error: expect(got_version_messages).to match_array(expected_version_messages)
  
    expected collection contained:  ["in:MessageAck", "in:Version", "out:MessageAck", "out:Version"]
    actual collection contained:    ["in:Version", "in:Watchdog", "out:MessageAck", "out:Version"]
    the missing elements were:      ["in:MessageAck"]
    the extra elements were:        ["in:Watchdog"]
```

**Comment by emiltin** [comment]
@otterdahl input?

The spec states that Version messages are exhcange first, then Watchdogs. Do we want to enforce that both Versions mesages are acknowledged before the Watchdogs are send? The current issue shows that's the ITC-2 sends the Watchdog before it acks the Version it receives.

**Comment by otterdahl** [comment]
In version 3.1.2 and 3.1.3 this isn't clear. And therefore I don't think we can't require it.

However, with version 3.1.4 this was clarified in the section **4.3. Transport of data**. The TLC's shoudn't send Watchdog before recieving the MessageAck from the version message.

**Comment by SwarcoPalm** [comment]
I'm just reviewing open issues and I believe this can be closed?

**Comment by emiltin** [comment]
The validator checks the sequence from 3.1.4. For earlier version, the sequence is not enforced. Closing this as the original issue refered to 3.1.2.
