### ISSUE TITLE
ITC-3 keep sending the same alarms

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#292]
It seems ITC-3 keeps sending the same alarms over and over. Needs more investigation

**Comment by sveitech** [comment]
Please report controller specific bugs or issues on our company portal. We do not track or monitor this repository for issues related to our implementation of the RSMP protocol.

**Comment by SwarcoPalm** [comment]
I'm just reviewing open issues and I believe this can be closed? The validator should warn on this and doesn't do anymore

**Comment by emiltin** [comment]
Right, looks like this was fixed on the controller, closing.
