### ISSUE TITLE
ITC-3 signal group component config?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#299]
A few tests fails appearently because the compomnent id for signal groups are not correct. What are the signal groups component ids in the TLC?

    is ordered to green with M0010 - Failed: command response 78ea0174 was rejected: Component ID not recognized.
    is ordered to red with M0011 - Failed: command response a969557f was rejected: Component ID not recognized.

**Comment by otterdahl** [comment]
The current ITC-3 config should be correct. So I think this issue can be closed.
