### ISSUE TITLE
Command test cases fail due to timeout (e.g. #<Async::TimeoutError:)

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#30]
Test cases for commands does not check for MessageNotAck.

I would recommend adding the following line:

`expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"`

just before this line:
`expect(response).to be_a(RSMP::StatusResponse)`

If a MessageNotAck is recieved, then a StatusResponse will never be recieved, causing a timeout

**Comment by GunnarRolander** [comment]
I presume it should be added just before 
`expect(response).to be_a(RSMP::CommandResponse)`

**Comment by otterdahl** [comment]
Yes. I believe that would work

**Comment by GunnarRolander** [comment]
I made the suggested changes and pushed them (see here: [commit](https://github.com/rsmp-nordic/rsmp_validator/commit/f2e9e1ef9fd0cf18ad8f3774925eed1d29fe0110)) but it seems like the timeout is happening before there's a chance to check if the message is acknowledged or not.

**Comment by otterdahl** [comment]
Right. It seems the timeout is happening while waiting for CommandResponse using the "wait_for_command_response" function. That function is part of the rsmp gem (lib/rsmp/site_proxy.rb).

I think a better place for the MessageNotAck check is before the wait_for_command_response() code block.

**Comment by GunnarRolander** [comment]
I see. 
Maybe I'm missing something, but won't the test in that case always fail since the response variable is initiated as nil and gets the actual response from the 'wait_for_command_response'-function?

**Comment by otterdahl** [comment]
You`re right. My mistake. I think the wait_for_command_response() function need to look for MessageNotAck, you like the wait_for_status_response() function does. The rsmp gem needs to be fixed.

**Comment by GunnarRolander** [comment]
Right, should do the same checks as the wait_for_status_response(), but with CommandResponse instead?
`if item[:message].type == 'MessageNotAck'
          next item[:message].attribute('oMId') == options[:message].m_id
elsif item[:message].type == 'CommandResponse'
          next item[:message].attribute('cId') == options[:message].attribute('cId')
end`

**Comment by emiltin** [comment]
Hi, you can use **```ruby** to syntax color and indent Ruby code.

**Comment by otterdahl** [comment]
> Right, should do the same checks as the wait_for_status_response(), but with CommandResponse instead?

Correct.
Don't forget the following line:
```ruby
item = @archive.capture(@task, options.merge(
        type: ['StatusResponse','MessageNotAck'],
```

**Comment by GunnarRolander** [comment]
This should be fixed with in this commit: [Updated wait_for_command_response](https://github.com/rsmp-nordic/rsmp/commit/6f0b96f660288ccfb7bd93b9fe73a739ec861223)

Need to verify it though.

**Comment by otterdahl** [comment]
Good work. However, it doesn't work quite yet. 

The `options[:message]` is not set. It should contain the full original RSMP message of the CommandRequest. This is needed since we need to verify that the MessageNotAck is the response to the CommandRequest. This is done using the MessageId (mId) of the CommandRequest and the corresponding originalMessageId (oMId) in MessageNotAck.

I've [updated the rsmp gem](f1b2c6a3c863dfe83eeaf4e073282f7025d3263a) and [added options[:message] ](0f7fc49edf584109dc220c04289806592442f580) which seems to fix the issue.

I think this issue can be closed now
