### ISSUE TITLE
ITC-3: Can't set an input to False with with M0006

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#309]
It is not possible to set an input to False with M0006

1. S0029 (forced input status) reports "00000..."
4. Setting input 2 with M0006 to status: True
3. S0003 (input status) reports "10000..."
4. Setting input 2 with M0006 to status: False
5. S0003 (input status) reports "10000..." (no change)

However, it is possible to force the input off using M0019

Tested with: ITC-3 v7.12.4 date 0-00-00 build 6278c141

**Comment by emiltin** [comment]
I think the TLC should default to a setting that makes the tests pass? Ie. if you don't configure "unforce-software-flag-default-state" it shoudl default to off?

**Comment by SwarcoPalm** [comment]
That would break a number of already installed systems. The current behaviour was the widely accepted one before the comment in the linked thread 2 weeks ago
