### ISSUE TITLE
alarm_spec.rb, test "A0302 can be acknowledged" should respect rsmp core version (hardcoded to 3.2 spec)

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#314]
This test assumes 3.2 core version and does not respect 3.1.2 API. It expects "Active" instead of "active", "Acknowledged" instead of "acknowledged", e.t.c.

Code:
```
    specify 'A0302 can be acknowledged', :programming, sxl: '>=1.0.7' do |example|
      Validator::Site.connected do |task,supervisor,site|
        prepare task, site
        alarm_code_id = 'A0302'   # what alarm to expect
        timeout  = Validator.config['timeouts']['alarm']

        log "Activating alarm #{alarm_code_id}"
        deactivate, component_id = with_alarm_activated(task, site, alarm_code_id) do |alarm, component_id|   # raise alarm, by activating input
          log "Alarm #{alarm_code_id} is now active on component #{component_id}"

          # verify timestamp
          alarm_time = Time.parse(alarm.attributes["aTs"])
          expect(alarm_time).to be_within(1.minute).of Time.now.utc

          # test acknowledge and confirm
          log "Acknowledge alarm #{alarm_code_id}"

          collect_task = task.async do
            RSMP::AlarmCollector.new(site,
              num: 1,
              query: {
                'aCId' => alarm_code_id,
                'aSp' => /Issue/i,
                'ack' => /Acknowledged/i,
                'aS' => 'Active'
              },
              timeout: timeout
            ).collect!
          end
```

The other alarm tests work correctly because they use the "with_alarm_activated" function which handles the core version discrepancies. The above test does not use that function.

**Comment by emiltin** [comment]
A regex pattern like `/Issue/i`which includes the `i` flag is don't case insensitive, so it should work for both version? The JSON Schema additionally verifies the casing depending on version.

**Comment by sveitech** [comment]
If I change our code to emit "Acknowledged, "Active", as compared to "acknowledge", "active", the test passes

**Comment by sveitech** [comment]
I guess its the "active" tests that is failing? That line is missing the "/i" part.

**Comment by sveitech** [comment]
No, it was not just the "/i" part. The test still fails, but works if I change our code to emit upper case.

**Comment by sveitech** [comment]
this seems to fix it: 

```
 'aS' => /Active/i
```

Instead of 

```
'aS' => 'Active'
```

**Comment by emiltin** [comment]
Right, seems the /i was just missing from the Active string

**Comment by sveitech** [comment]
Is must specifically NOT be a string. You have to remove the quotes around Active.
