### ISSUE TITLE
'A0302 can be acknowledged', checks for the wrong alarm specialization (aSp)

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#322]
When sending an alarm acknowledge to a device, the device must reply back with the "aSp" field set to "Acknowledge".

This test checks if "aSp" is set to "Issue", which is wrong.

See https://rsmp-nordic.org/specification, core version 3.2 pdf, page 21.

As an example, see the "'A0302 can be suspended and resumed' test, which correctly expects "aSp" to be "Suspend".

**Comment by emiltin** [comment]
Thanks. Looking at the docs, I also wonder about this: https://github.com/rsmp-nordic/rsmp_core/issues/112

**Comment by emiltin** [comment]
Should be fixed now. Feel free to reopen if there are remaining problems.
