### ISSUE TITLE
All test hub equipment is offline

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#329]
The EC-2, ITC-2 and ITC-3 in our test hub are all offline. Unfortunately it seems we've had a lot of problems like this in the last year.

Can the come up with a more stable setup..?

We can also consider how to collect and publish uptime statistics for each device. Perhaps simply as percent of times the equipment did connect when we run tests.

Apart from the test results themselves, uptime is an important factor when you want to know how reliable equipment from different vendors is.

**Comment by otterdahl** [comment]
The ITC-3 is now up and running.
The ITC-2 and EC-2 most likely never be online since the development has stopped on those TLC's.

I think this issue can be closed.
