### ISSUE TITLE
Watchdog setting clock during clock_spec tests

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#355]
During the clock_spec tests, if the watchdog interval is set too low, a watchdog message may be sent to the device during the clock tests, which may break the tests if the device is set to change clock on watchdog messages.

Perhaps the clock_spec tests should forcibly disable the watchdog messages, or at least require somehow in the documentation, that watchdog time-setting has been disabled.

**Comment by emiltin** [comment]
Good point. I suggest we disable sending watchdogs during the tests.

**Comment by emiltin** [comment]
Fixed with #355
