### ISSUE TITLE
Possible specification error in M0003, for SXL 1.0.13

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#356]
https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/blob/1.0.13/sxl_traffic_controller.md#M0003

The M0003 object states that the situation number goes from 1-255, but the rsmp_validator sets the value to 0, when trying to revert the situation to automatic mode.

From the validator logs:
 Sent CommandRequest  {"mType":"rSMsg","type":"CommandRequest","cId":"AA+BBCCC=DDDEEFFF","arg":[{"cCI":"M0003","cO":"setTrafficSituation","n":"status","v":"False"},{"cCI":"M0003","cO":"setTrafficSituation","n":"securityCode","v":"default"},{"cCI":"M0003","cO":"setTrafficSituation","n":"traficsituation","v":"0"}],"mId":"e9ddc99e-1ca1-41d7-88b7-fa11f5e75bb9","ntsOId":"","xNId":""}

**Comment by emiltin** [comment]
I agree, the the validator should not use 0. I guess this was done because the value is not defined in the sxl when setTrafficSituation = false. Should we use 1? In any case, this needs to be fixed first in the schema.

**Comment by emiltin** [comment]
The correct range 1-255 is already defined in later version of the sxl yaml. But because integers are send as strings (instead of plain json numbers), there's no straightforward way to validate the values. It could be done using regex, but it's a bit ackward.
