### ISSUE TITLE
Alarm test case need to check timestamp

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#36]
The alarm test case needs to check the timestamp of any received alarms, so that they aren't actually old alarms.

**Comment by otterdahl** [comment]
I've checked the logs, and I get this error after commit b088db7fd33f2c1e70273e5a5a9fb16866415163

```
1m29s    error: Async::Task [oid=0x10cc] [pid=343771] [2020-11-13 14:57:06 +0100]
               |   NoMethodError: undefined method `attributes' for #<Hash:0x000055a3446577b8>
               |   → /home/i0davla/trv/rsmp/rsmp_validator/spec/site/alarm_spec.rb:19 in `block (3 levels) in <top (required)>'
               |     /home/i0davla/trv/rsmp/rsmp_validator/spec/support/test_site.rb:79 in `block in connected'
               |     /home/i0davla/trv/rsmp/rsmp_validator/spec/support/test_site.rb:24 in `block in within_reactor'
```

**Comment by GunnarRolander** [comment]
Is using 'attributes' the wrong way to get to the timestamp and schema of the response in the case of alarms?
Since it works that way with the commands and statuses I just figured it would probably work the same way with the alarms.

**Comment by otterdahl** [comment]
Looking at `site_proxy.rb` is seems that `wait_for_alarm` returns differently than `wait_for_status_response` and `wait_for_command_reponse`.

`wait_for_alarm` returns:
```ruby
{ message: item[:message], status: matching_alarm }
```

`wait_for_status_response` and `wait_for_command_reponse` returns:
```ruby
item[:message] if item
```

I don't know why this difference exists, but I fixed alarm_spec in commit https://github.com/rsmp-nordic/rsmp_validator/commit/5d2aee8077db1c3c00c99461be7abfce53de4f83

Now I get the following error instead:
```
 1m23s    error: Async::Task [oid=0x1004] [pid=349018] [2020-11-13 15:32:27 +0100]
               |   NoMethodError: undefined method `utc' for "1970-01-01T00:30:59.000Z":String
               |   → /home/i0davla/trv/rsmp/rsmp_validator/spec/site/alarm_spec.rb:21 in `block (3 levels) in <top (required)>'
               |     /home/i0davla/trv/rsmp/rsmp_validator/spec/support/test_site.rb:79 in `block in connected'
               |     /home/i0davla/trv/rsmp/rsmp_validator/spec/support/test_site.rb:24 in `block in within_reactor'
               |     /var/lib/gems/2.7.0/gems/async-1.23.0/lib/async/task.rb:255 in `block in make_fiber'
```

**Comment by otterdahl** [comment]
After the latest commit I don't get any errors anymore, but it still doesn't quite work right.

Looking at the validator.log:
The timestamp (aTs) is `1970-01-01T10:24:12.000Z`, but it still thinks it's OK with `alarm confirmed after 70s`

**Comment by GunnarRolander** [comment]
I see. That is odd. I'll look into it.

**Comment by otterdahl** [comment]
Wait. My bad.
I get the following error:
```
 6.76s    error: Async::Task [oid=0x1004] [pid=256048] [2020-11-17 17:54:51 +0100]
               |   NoMethodError: undefined method `minute' for 1:Integer
               |   → /home/i0davla/trv/rsmp/rsmp_validator/spec/site/alarm_spec.rb:20 in `block (3 levels) in <top (required)>'
               |     /home/i0davla/trv/rsmp/rsmp_validator/spec/support/test_site.rb:79 in `block in connected'
               |     /home/i0davla/trv/rsmp/rsmp_validator/spec/support/test_site.rb:24 in `block in within_reactor'
               |     /var/lib/gems/2.7.0/gems/async-1.23.0/lib/async/task.rb:255 in `block in make_fiber'
```

**Comment by otterdahl** [comment]
I've added err.log to https://otterdahl.org/rsmp_validator_log/

You can check err.log for any errors that has occurred during each test run. The latest [is here](https://otterdahl.org/rsmp_validator_log/err-2020-11-18_09-00-49.log)

**Comment by otterdahl** [comment]
Commit 2d0e02c1517f951246fdd5df17c5bcdc9c72ef49 fixes it
