### ISSUE TITLE
clock_spec: 'is used for alarm timestamp' does not reset alarm-reception time, when changing the clock

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#376]
This test throws warnings "Rejected alarm message,timestamp is earlier than previous alarm", because the test does not reset the time-of-last-reception when it sends the set-clock command.

When connecting, RSMP sends out all current alarms, with current timestamp (i.e. 2024). Then the test sets the device clock to 2020, so of course the alarms are older than last received.

This can be validated by changing the test to set the time to 2025 instead of 2020, in which case the warnings disappear.

This line in the test:

`  with_clock_set CLOCK do  `

should also reset the alarm-reception clock.

**Comment by emiltin** [comment]
Should be fixed in the latest main branch, let me know if it works for you.

**Comment by emiltin** [comment]
closing
