### ISSUE TITLE
Alarm test case fails if alarm already active

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#39]
The alarm test case fails if the alarm is already active.

If any alarms are present, the alarms needs to be deactivated before it is possible to activate it again

**Comment by emiltin** [comment]
can all alarms be deactivated when connecting?

**Comment by otterdahl** [comment]
Yes. the alarms can be cleared.
I've experimented with a solution, but I haven't checked if it fixes the problem.

**Comment by emiltin** [comment]
alarm tests now all use the helper with_alarm_activated(), which first deactivates the alarm before activating.
