### ISSUE TITLE
Proposed placement of profile info in SXL file

### ISSUE THREAD

**Issue by GunnarRolander** [rsmp-nordic/rsmp_validator#41]
This is a proposed way to place profile data in the SXL YAML file, which is to be used when running tests filtered by profile.

```statuses:
      S0001:
        description: Signal group status
        arguments:
          signalgroupstatus:
            type: string
            description: Signal group status as text field
            range: "[text]"
          cyclecounter:
            type: integer
            description: Cycle counter
            range: "[0-999]"
          basecyclecounter:
            type: integer
            description: Base cycle counter
            range: "[0-999]"
          stage:
            type: integer
            description: Current stage (isolated)
            range: "[0-999]"
        profiles: ["TRV", "Baseline"]
      S0002:
        description: Detector logic status
        arguments:
          detectorlogicstatus:
            type: string
            description: Detector logic status as text field
            range: "[text]"
        profiles: ["Baseline"]
      S0003:
        description: Input status
        arguments:
          inputstatus:
            type: string
            description: Input status as text field
            range: "[text]"
          extendedinputstatus:
            type: string
            description: Extended input status as text field
            range: "[text]"
        profiles: ["Vejdirektoratet"]```

**Comment by emiltin** [comment]
Can you explain this profile element? It seems this is not directly part of the SXL?

**Comment by GunnarRolander** [comment]
We're devising a way to run a subset of all the tests based on the requirements of different actors such as Trafikverket and Vejdirektoratet. To accomplish this we need a way to map the tests to the profiles. Adding a profile element to each command/status is one way we discussed..

**Comment by emiltin** [comment]
I would suggest to keep that out of the SXL.
An option is to tag rspec tests in the rsmp_validator with the profiles. Then you can easily run a specific set of tests.

**Comment by otterdahl** [comment]
I think there are several use cases for profile info, not just which tests to run. We have discussed that this needs to somehow be part of the documentation. We frequently get questions from vendors which of the alarms/statuses/commands that are required and which are optional. If there is any differences between road authorities, etc.

I think we should discuss this at the next tech board meeting.

**Comment by emiltin** [comment]
profiles will be handled by rspec tags
