### ISSUE TITLE
Actions-Runner Configuration + Validation of RSMP Core version 3.2.2, S.X.L 1.2.1 (latest release)

### ISSUE THREAD

**Issue by mariusrazvanplugaru** [rsmp-nordic/rsmp_validator#417]
Hi. 
We are trying to configure a new PC with the runner active to stay ONLINE 24/24 for RSMP validator tests. We want to validate the last version of SXL-RSMP core.
We try to configure the runner with the token sended by you but the result is: 

Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration' (Request Id: ACD4:245268:3482129:3529A76:66CF1B53)

What could be the problem?
Thank you!

**Comment by emiltin** [comment]
We need to configure a new runner. Is it a linux machine? And does it have x64, ARM or ARM64 archictecure?

**Comment by mariusrazvanplugaru** [comment]
Is an Ubuntu 22.04 x86_64. Thank you!

**Comment by emiltin** [comment]
Installing:
```
# Create a folder
$ mkdir actions-runner && cd actions-runner
# Download the latest runner package
$ curl -o actions-runner-linux-x64-2.319.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.319.1/actions-runner-linux-x64-2.319.1.tar.gz
# Optional: Validate the hash
$ echo "3f6efb7488a183e291fc2c62876e14c9ee732864173734facc85a1bfb1744464  actions-runner-linux-x64-2.319.1.tar.gz" | shasum -a 256 -c
# Extract the installer
$ tar xzf ./actions-runner-linux-x64-2.319.1.tar.gz
```


Configure. I'll send you the token by email:
```
# Create the runner and start the configuration experience
$ ./config.sh --url https://github.com/rsmp-nordic/rsmp_validator --token <token>
Copied! # Last step, run it!
$ ./run.sh
```

**Comment by mariusrazvanplugaru** [comment]
Thank you! Now it works, it was the token. When you are availableto test the new version. core version 3.2.2 SXL version 1.2.1? I can send you the new configuration or you can modify the existent with the new sxl and core version. We want also to associate the green flag on https://rsmp-nordic.org/compliance/ to this runner.
Thank you!
KR,

**Comment by emiltin** [comment]
I've have a bit of meetings today, but you're welcome to create a PR with changes to the config/semaforica_cartesio.yaml file. Then I can review and merge it.
Once a test has been run I'll update the flag on the compliance page to point to the new runner.

**Comment by emiltin** [comment]
For now you need to specify the core and sxl version in the config at https://github.com/rsmp-nordic/rsmp_validator/blob/main/config/semaforica_cartesio.yaml#L72.

Later we will update the validator to test on a matrix of core versions.

**Comment by emiltin** [comment]
> Modify made on that file. Please let me know when you are able to start the test so i activate the runner. KR,

OK, put please open a pull request with the changes.

**Comment by mariusrazvanplugaru** [comment]
I think now is created a pull request

**Comment by mariusrazvanplugaru** [comment]
Thank you for help and validating this new version! Please tell me when you associate the green flag with this new version so i can close this issue, or you can close also i think! 

KR

**Comment by emiltin** [comment]
The flag on the compliance page shows the status of the latest nighly run. After the next run tonight it should be green (assuming tests pass).

The reasons we show the status of the nighly run (which is run from the main branch) is to avoid red flags while 
we're fixing/experimenting in a branch.
