### ISSUE TITLE
TECSEN TMacs Platform validation

### ISSUE THREAD

**Issue by mariusrazvanplugaru** [rsmp-nordic/rsmp_validator#419]
Hi. Here I open a new 'question' for the validation of our TMacs Platform. 

I ask if it is possible and which tests will be performed as for the supervisor's OFFLINE validator there are only 2 3 connection tests. 

Furthermore, we also want to associate a green flag for the platform on the site https://rsmp-nordic.org/compliance/. 
Can we use the same runner or 2 different runners with two different tokens?

Thank you!
KR,

**Comment by mariusrazvanplugaru** [comment]
Hi, Yes is a linux x86 machine. After we get this new token, if is possible we want to change also the TLC token for connect the runner with a server (that is allways online) instead to mantain a PC open. Thank you!
KR,

**Comment by emiltin** [comment]
I've emailed you tokens.

**Comment by mariusrazvanplugaru** [comment]
Hi. I'm trying to connect the Cartesio with the new token but it give me response status code 404. It is already active?

**Comment by emiltin** [comment]
Did you run `./config.sh --url https://github.com/rsmp-nordic/rsmp_validator --token <toklen`? I don't see the new runner yet.

**Comment by mariusrazvanplugaru** [comment]
Hi. I saw that the automatically test failed. Could you restart now the action for see why? I activate on our server an automatic service for the runner and maybe the problem is this. I don't know! Thank you!

**Comment by mariusrazvanplugaru** [comment]
Ok i understand maybe the problem. The runner of our Cartesio connects to the runner of the TMacs Platform. 
Could we change the Cartesio port from 12111 to 13111 for example?

**Comment by emiltin** [comment]
Yes, I suggest you test TMacs on port 13111 by opening a PR with a change to the config at https://github.com/rsmp-nordic/rsmp_validator/blob/main/config/tecsen_tmacs_supervisor.yaml. You would of  course have to change the TMac itself to listen on port 13111.

**Comment by mariusrazvanplugaru** [comment]
Sorry, i already changed the Cartesio config opening a PR. Is good also? Could we test that? if it runs? Thank you!

**Comment by emiltin** [comment]
PR merged

**Comment by emiltin** [comment]
Done.
