### ISSUE TITLE
Test case: Check startup interval

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#42]
Add a functional test when starting the controller.

The signal group status should begin with this sequence:
* Start-up interval 1: minimum 3 seconds
* Start-up interval 2: minimum 3 seconds
* Start-up interval 3: minimum 3 seconds

In Sweden, this is defined by Transportstyrelsens författningssamling [TSFS](https://www.transportstyrelsen.se/TSFS/TSFS%202014_30k.pdf), chapter 2, §17 (page 4)

**Comment by otterdahl** [comment]
Test cases for start-up has been added, but time minimum durations needs to be verified

**Comment by emiltin** [comment]
> Test cases for start-up has been added, but time minimum durations needs to be verified

This would be an enhancement of the existing checks for startup sequence?

**Comment by otterdahl** [comment]
yes

**Comment by emiltin** [comment]
implemented. if we need to improve the tests, we can open new issues
