### ISSUE TITLE
ITC-3 failures on core 3.1.2

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#437]
We tried testing the ITC-3 on all the core version that is says it supports.

We see these failures on 3.1.2:

```
rspec ./spec/site/tlc/alarm_spec.rb:29 # Site::Traffic Light Controller Alarm Alarm A0302 is raised when input is activated
rspec ./spec/site/tlc/alarm_spec.rb:58 # Site::Traffic Light Controller Alarm A0302 can be acknowledged
rspec ./spec/site/tlc/alarm_spec.rb:109 # Site::Traffic Light Controller Alarm A0302 can be suspended and resumed
rspec ./spec/site/tlc/clock_spec.rb:220 # Site::Traffic Light Controller Clock is used for alarm timestamp
rspec ./spec/site/tlc/signal_groups_spec.rb:45 # Site::Traffic Light Controller Signal Group red/green predictions is read with S0025
```

We can open individual issues for each as needed.

Test log:
https://github.com/rsmp-nordic/rsmp_validator/actions/runs/10808667811/job/29982139096

**Comment by SwarcoPalm** [comment]
Where do we find the associated yamls for the test?

**Comment by emiltin** [comment]
Do you mean test configs? They are in https://github.com/rsmp-nordic/rsmp_validator/tree/main/config

**Comment by SwarcoPalm** [comment]
The ITC-3 one only specifies 3.2.0 here, does the matrix config simply switch out this value and hold the rest fixed?

**Comment by emiltin** [comment]
The workflow set the env CORE_VERSION for eaech test job, which overrides the core_version specified in the test config yaml.
I just need to remove the core_version in the yaml, thanks for the reminder.

**Comment by emiltin** [comment]
> The ITC-3 one only specifies 3.2.0 here, does the matrix config simply switch out this value and hold the rest fixed?

Yes, the same config is used for all core version test jobs.

**Comment by sveitech** [comment]
I can see this schema error in one of the tests:

 2024-09-11T09:19:10.023Z  40408  AA+BBCCC=DDD         AA+BBCCC=DDDDL002    3e6d  Received invalid Alarm schema errors: /aS, enum,  {
    "mType": "rSMsg",
    "type": "Alarm",
    "mId": "3e6da1c7-65ca-435b-91cb-0da47b9b743c",
    "ntsOId": "",
    "xNId": "",
    "cId": "AA+BBCCC=DDDDL002",
    "aCId": "A0302",
    "xACId": "Control Block 2: Det Logic 2 (<DET LOGIC NAME>) has an OFF failure.",
    "xNACId": "",
    "aSp": "Issue",
    "ack": "notAcknowledged",
    "aS": "inactive",
    "sS": "notSuspended",
    "aTs": "2020-09-29T17:29:52.228Z",
    "cat": "D",
    "pri": "3",
    "rvs": []
}
    2024-09-11T09:19:10.024Z  40408  AA+BBCCC=DDD         -                    -     Sent MessageNotAck for Alarm 3e6d  {"mType":"rSMsg","type":"MessageNotAck","rea":"schema errors: /aS, enum,","oMId":"3e6da1c7-65ca-435b-91cb-0da47b9b743c"}
    
    But is this a schema error? Am I reading the output correctly, that it is complaining about the "aS" field? Why is this not compliant? In core 3.1.2, "inactive" is the correct value (https://rsmp-nordic.github.io/rsmp_core/3.1.2/applicability/basic_structure.html#alarm-messages)

**Comment by emiltin** [comment]
Right, older version of core very not case-sensitive. Validating case-insesitively is impractical, so we're allowing a certain set of variations in the schema, currently these:
```yaml
    "aS" : {
      "description" : "Active status",
      "type" : "string",
      "enum" : [ "inActive", "Active",
                 "InActive", "active" ]
    },
```

I guess we should alllow "inactive"?

**Comment by sveitech** [comment]
well, that would depend on the RSMP spec, I guess? :) Are we in agreement that the spec for 3.1.2 says the correct value should be "inactive" and "active"? as per this page: https://rsmp-nordic.github.io/rsmp_core/3.1.2/applicability/basic_structure.html#alarm-messages

**Comment by emiltin** [comment]
Yes, however, some implementations used different casings. Since we did not explicitly require enums to parsed case-sensitively, it was not clear if this was against the spec, and we choose to allow case variations on earlier core versions.

**Comment by sveitech** [comment]
wouldnt the correct course of action then be to allow case-insensitivity across the board for that particular case? If the 3.1.2 spec is case-insensitive, make the test case-insensitive.

**Comment by emiltin** [comment]
Well, as mentioned, it's not trivial with json schema. But I agree the spec uses "inactive" and we should therefore of course allow that case variation.

**Comment by emiltin** [comment]
Instead of allowing all casing, incliuding odd ones like iNaCtiVE, that we're not usedd by any equipment, we choose a programtic aproach and allowed a set of casings  for enums, in our json schema files.

**Comment by emiltin** [comment]
Note that the only allowed casing from 3.2.0 is "inActive". Yes, I find that casing a bit odd, but at least only one variation is allowed.

**Comment by emiltin** [comment]
In principle. But since only a limited set of case variations where used in practice, we chose to just accept those. Because matching a enum value case-insentivitely is not possible in json schema. There are some hacks, but they might not work in all implementations.

**Comment by sveitech** [comment]
So what is the conclusion? Will you add "inactive" to the list to comply with the 3.1.2 spec?

This should fix the failing tests mentioned in #437 and #438.

**Comment by emiltin** [comment]
Merged, and I rebased this PR on main. But not all errors went away.

**Comment by sveitech** [comment]
Thanks. I think the "inactive" field needs to be added to the alarm_suspended_resumed.json schema file as well.

**Comment by emiltin** [comment]
schema was, tests now run without errors
