### ISSUE TITLE
Recent problems on validator

### ISSUE THREAD

**Issue by mariusrazvanplugaru** [rsmp-nordic/rsmp_validator#457]
Hi! Have you recently changed anything about the validators like libraries or more memory usage or something else? We have problems for both runner (TMacs and Cartesio) and we try to undersdand why they used to go and now they don't.
On our side we haven't changed anything.
Best regards,

**Comment by mariusrazvanplugaru** [comment]
@emiltin i saw from logs that is the same problem on "/opt/hostedtoolcache/Ruby/3.3.6/x64/bin/bundle"

**Comment by emiltin** [comment]
A guess is that it could be related to updates in ruby 3.3.5 or 3.3.6, or to a corrupted gem cache.

Perhaps try to clear the gem cache, see https://github.com/ruby/setup-ruby?tab=readme-ov-file#dealing-with-a-corrupted-cache.

Or try to remove Ruby, so it will be reinstalled.

**Comment by mariusrazvanplugaru** [comment]
I cleared the cache. Could you restart the validator tests for see if it works?

**Comment by mariusrazvanplugaru** [comment]
Hi @emiltin! Could you restart the process of validator? Right now i have installed also ruby on the last version and cleared the cache. Thank you!

**Comment by emiltin** [comment]
I restarted both the TMacs and the Cartesio runners. The Cartesio now passes tests.

The TMacs runner now successfully installs ruby and all gems, but the tests fail because the supervisor (TMacs cannot be reached):
Aborting: Could not connect to supervisor within 30s

Can you check that's it's running and listening on the correct port?

**Comment by mariusrazvanplugaru** [comment]
Yes, we saw and solved that. We see it on the next test. Thank you!

**Comment by emiltin** [comment]
OK, i restarted the tes job.
