### ISSUE TITLE
Test case "M0001" failed with "Did not receive alarm"

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#47]
In the previous run, test case "M0001 set dark mode" failed with the error message. "Did not receive alarm" (from test case 'Acknowledge alarm')
```
     Failure/Error:
       expect do
         response = site.wait_for_alarm component: component, aCId: 'A0302',
           aSp: 'Issue', aS: 'Active', timeout: RSMP_CONFIG['alarm_timeout']
       end.to_not raise_error, "Did not receive alarm"

       Did not receive alarm
     # ./spec/site/alarm_spec.rb:48:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:95:in `block in connected'
     # ./spec/support/test_site.rb:21:in `block in within_reactor'
     # /var/lib/gems/2.7.0/gems/async-1.28.3/lib/async/task.rb:265:in `block in make_fiber'
```
Why did this happen?

**Comment by emiltin** [comment]
Yes this is suspicious. This test should not be waiting for alarms.

**Comment by emiltin** [comment]
The alarm test call out to shell to try to activate an alarm in the simulator. For this reason I have been skipping these test when testing locally against the Ruby TLC.

I suspect calling out to shell might be interfering with the Async concurrent mechanism, but not sure.

**Comment by emiltin** [comment]
What's odd is that the backtrace in the failure points to code in spec/site/alarm_spec.rb, but the failing rspec test is actually in spec/site/command.spec.rb. alarm_spec.rb was run before command.spec.rb. 

We're keeping an Async reactor across rspec tests to keep an RSMP supervisor running. All tests should be run in separate async tasks that are removed after each rspec test. Maybe that alarm wait tas was added to the supervisor task by mistake, and therefore lives on and interferes with later tests?

**Comment by emiltin** [comment]
wait_for_alarm is an older method and it did not set the correct parent task. I've fixed it. Let's hope this get's rid of the problem.

**Comment by otterdahl** [comment]
This issue seems fixed with the latest changes

**Comment by ioquatix** [comment]
Great.
