### ISSUE TITLE
Latest test-run (add_S0098) trips up several tests

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#474]
The latest test-runner on branch S0098 seems to trip up several tests. The logs seem to indicate that this is an error in the validator, during the call to site.send_command.

Can you please confirm if this is the case?

![Clipboard - December 18, 2024 1_53 PM](https://github.com/user-attachments/assets/97e31b35-6f06-48ca-a0e3-e4641821cfb7)

**Comment by emiltin** [comment]
Yes, some tests are failing, complaining as you show refering to invalid byte sequences "\xE2" on US-ASCII. The error does not. occur with the Ruby Gem TLC emulator.

I don't know yet what cases it.  In #473, I updating just Ruby and Gems, and fixing an issue with plan nrs, to see if the error is related ruby/gem version.

**Comment by emiltin** [comment]
Is the US-ASCII encoding used as the OS encoding on the machine where your GitHub. runner is?

**Comment by emiltin** [comment]
The "\xE2" errors occur in #473, going to continue investigation there.

**Comment by sveitech** [comment]
> Is the US-ASCII encoding used as the OS encoding on the machine where your GitHub runner is installed?

Regarding US-ASCII encoding, how can I check? Is this something that must be configured in the dockerfile?

**Comment by emiltin** [comment]
@sveitech what's the OS character encoding on the machine where you github runner is intalled?

**Comment by emiltin** [comment]
> > Is the US-ASCII encoding used as the OS encoding on the machine where your GitHub runner is installed?
> 
> Regarding US-ASCII encoding, how can I check? Is this something that must be configured in the dockerfile?

Try running `locale`in the container.

**Comment by emiltin** [comment]
Check also this post: https://web.archive.org/web/20230323021946/http://jaredmarkell.com/docker-and-locales/

**Comment by sveitech** [comment]
I also found this: https://github.com/Shopify/bootsnap/issues/444

We can fix it in the docker container, but... I think that the binary encoding of a ruby program should not rely on any settings on the host-machine. This is too fragile. I think the proper way forward is to fix the encoding of strings in the ruby program itself. Is it not possible to force ruby to use a certain ascii encoding when converting to binary, instead of relying on host settings?

**Comment by emiltin** [comment]
Thanks for the link.
I need to first understand the issue. Did you check what `locale` returns in your container? 
I also don'y yet understand where there "\xE2" comes from.

**Comment by emiltin** [comment]
Thank you, great find.

**Comment by emiltin** [comment]
I'm still interested in knowing what 'locale' returns in your container.

**Comment by emiltin** [comment]
Removing all non-ascii characters from the schema repo seems to have solved the issue, at least there are no errrors in this run: https://github.com/rsmp-nordic/rsmp_validator/actions/runs/12395320472/job/34600753884?pr=473

**Comment by sveitech** [comment]
I tracked the issue as far as schema validation in the rsmp_schema gem, file schema.rb:

```
  # validate an rsmp messages using a schema object
  def self.validate_using_schema message, schema
    raise ArgumentError.new("message missing") unless message
    raise ArgumentError.new("schema missing") unless schema
    unless schema.valid? message
      schema.validate(message).map do |item|
        [item['data_pointer'],item['type'],item['details']]
      end
    else
      []
    end
  end
```

Seems like the call to validate fails to parse the schema strings

**Comment by emiltin** [comment]
Yes I think it's because some schema files included non-ascii characters.
