### ISSUE TITLE
sxl version tagging

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#48]
I've added support for specifying in what sxl versions a spec is expected to be implemented. Eg:

```ruby
  it 'M0013 activate a series of inputs', sxl: '>=1.0.8' do |example|
  end

  it 'M0014 set command table', sxl: '>=1.0.13' do |example|
  end
```

You can use these restriction operators: =, !=, >, <, >=, <=, ~>, see https://devalot.com/articles/2012/04/gem-versions.html. It uses the Gem utilities to match verison, but otherwise this has noting to to with gems.

 You can combine them as well:

```ruby
  it 'Some depreciated command', sxl: ['>=1.0.7','<1.0.13'] do |example|
  end
```

The sxl version in the spec is matched against the sxl version of the equipment being tested, which is specified in the 'sxl_version' config for the site. Here's the current config/swarco.yaml:

```yaml
supervisor:
  sites:
    :any:
      sxl_version: 1.0.7
      plans:
        - 8
        - 9
...
```

If no sxl version is specified for the site, the sxl tags are ignored and all tests will be run.

@GunnarRolander and @otterdahl: If you like this approach, we need to to through the specs and tag them. I've tagged most already according to what I could glean from https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/blob/master/ChangeLog.md, but not all specs have and sxl tag yet. I think there are also a few that have been depreciated in never versions?

**Comment by emiltin** [comment]
If you're curious, this is implement by using RSpec's config.filter_run_excluding, and passing a lambda that will be evaluated for each spec:
https://github.com/rsmp-nordic/rsmp_validator/blob/master/spec/support/spec_helper.rb#L133

**Comment by emiltin** [comment]
A useful option when running rspec is --dry-run, which will show you what it's going to run, without actually running tests. You can combine with --format d to get an easy to read list of what's going to be run (which depends on the sxl_version you set in the config file).

```
code/rsmp_validator % be rspec spec/site --format d --dry-run 
Using test config config/ruby.yaml
Warning: Config 'scripts' is missing from config/ruby.yaml
Run options: exclude {:sxl=>#<Proc: ./spec/support/spec_helper.rb:140>}

RSMP site alarm
  A0302 detector error (logic error)
  Acknowledge alarm

RSMP site commands
  M0001 set yellow flash
  M0001 set dark mode
  M0002 set time plan
  M0003 set traffic situation
  M0004 restart
  M0005 activate emergency route
  M0006 activate input
  M0007 set fixed time
  M0008 activate detector logic
  M0010 start signal group
  M0011 stop signal group
  M0012 request start/stop of a series of signal groups
  M0013 activate a series of inputs
  M0103 set security code
  M0104 set date
  Send the wrong security code

RSMP site connection
  Version 3.1.1
    exchanges correct connection sequence
  Version 3.1.3
    exchanges correct connection sequence
  Version 3.1.4
    exchanges correct connection sequence

RSMP site disconnect
  disconnects if watchdogs are not acknowledged
  disconnects if no watchdogs are send

RSMP site status
  S0001 signal group status
  S0002 detector logic status
  S0003 input status
  S0004 output status
  S0005 traffic controller starting
  S0006 emergency stage
  S0007 controller switched on (dark mode=off)
  S0008 manual control
  S0009 fixed time control
  S0010 isolated control
  S0011 yellow flash
  S0012 all red
  S0013 police key
  S0014 current time plan
  S0015 current traffic situation
  S0016 number of detector logics
  S0017 number of signal groups
  S0018 number of time plans
  S0019 number of traffic situations
  S0020 control mode
  S0021 manually set detector logic
  S0091 operator logged in/out OP-panel
  S0092 operator logged in/out web-interface
  S0095 version of traffic controller
  S0096 current date and time
  S0201 traffic counting: number of vehicles
  S0202 traffic counting: vehicle speed
  S0203 traffic counting: occupancy
  S0204 traffic counting: classification

RSMP site status
  responds to valid status subscription

RSMP site commands
  M0001 set yellow flash

RSMP site status
  responds with NotAck to invalid status request code
  responds with NotAck to invalid status request name

Finished in 0.01158 seconds (files took 0.69054 seconds to load)
56 examples, 0 failures
```

**Comment by otterdahl** [comment]
> If you like this approach, we need to to through the specs and tag them. I've tagged most already according to what I could glean from https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/blob/master/ChangeLog.md, but not all specs have and sxl tag yet. I think there are also a few that have been depreciated in never versions?

I like this approach. I think that it is clear and just what we need.

I think `S0018` (number of time plans) is depreciated and replaced by `S0022` (list of time plans), but this is  not really officially documented yet.

**Comment by otterdahl** [comment]
I've added additional tags with commit 412dc243a7a732f376831563b488a7c7fd4fe55a

**Comment by emiltin** [comment]
sweet

**Comment by emiltin** [comment]
What sxl version requires which core version? I could find that info anywhere, and I need it to tag the test in connect_spec.rb

**Comment by otterdahl** [comment]
> What sxl version requires which core version? I could find that info anywhere, and I need it to tag the test in connect_spec.rb

Since we haven't changed the format of sxl in any significant way, there is no specific requirement. You can mix and match SXL and RSMP versions as you like.

**Comment by emiltin** [comment]
ok. so all sxl versions should check the connection sequest for all supported core versions? I guess te equipment config should specify the supported core versions.

**Comment by otterdahl** [comment]
Yes. Alternatively the core versions that the simulator sends in the handskake (version) could be used

**Comment by otterdahl** [comment]
> Since we haven't changed the format of sxl in any significant way, there is no specific requirement. You can mix and match SXL and RSMP versions as you like.

I almost forgot. We did made changes to datatypes in RSMP 3.1.3 where we removed ambiguous data types such as "raw", "scale" and "ordinal". SXL versions earlier than 1.0.15 still used "ordinal". So technically, SXL versions <1.0.15 requires RSMP <=3.1.2.

**Comment by emiltin** [comment]
closing. if the requirement that SXL versions <1.0.15 requires RSMP <=3.1.2 is important, we can open a new issue. for that
