### ISSUE TITLE
swarco simulator log is truncated

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#53]
The latest run starsted at 9:08, according to the validator log:
```
Running test ./spec/site/alarm_spec.rb:9 - RSMP site alarm A0302 detector error (logic error)
2021-01-21 09:08:33 UTC                                    Connecting
...
```

But the simulator logs starts at 09:14:

```
(2021-01-21 09:14:58) : [INFO]	 RECEIVING : {"mType":"rSMsg","type":"StatusRequest","ntsOId":"","xNId":"","cId":"KK+AG9998=001TC000","sS":[{"sCI":"S0096","n":"year"},{"sCI":"S0096","n":"month"},{"sCI":"S0096","n":"day"},{"sCI":"S0096","n":"hour"},{"sCI":"S0096","n":"minute"},{"sCI":"S0096","n":"second"}],"mId":"733a0390-f556-4e7e-855c-c4f946e53738"}
```

Might it be truncated, or rotated at the wrong time?

**Comment by otterdahl** [comment]
I clear the log file before each run (reducing it's size to 0 bytes without deleting it) while the rsmp service is running. I'm unsure what causes this issue. Let's keep an eye on this.

The alternative is to not touch to the log file.

**Comment by emiltin** [comment]
we're now using github ci, so this might be irrelevant?

**Comment by otterdahl** [comment]
Maybe. I no longer clear the log file before each run. I just upload the current state of the log file. Reopen this issue if this remains a problem
