### ISSUE TITLE
Setting up Github continous integration (CI) with self-hosted runner

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#55]
I'm working on setting up continuous integration (CI) with the simulators at the moment. I'll post updates in this issue

**Comment by emiltin** [comment]
cool

**Comment by otterdahl** [comment]
The self-hosted runner is available at https://github.com/rsmp-nordic/rsmp_validator/actions
It is set to run on push, pull-request or manually.

To do:
[x] Set up self-hosted runner
[ ] Clear the logs before run
[ ] Make sure the validation.log is shown
[ ] Make sure the simulator log is shown

**Comment by otterdahl** [comment]
This means that right now the self-made simulator runner script is no longer is active. So no new log files will show up at https://otterdahl.org/rsmp_validator_log/

**Comment by emiltin** [comment]
It would to great to run tests against the ruby TLC as well

**Comment by emiltin** [comment]
i can see the rspec output, but where are the other log files?

**Comment by otterdahl** [comment]
> i can see the rspec output, but where are the other log files?

It is saved as an "artifact" and shown below the log:

![1](https://user-images.githubusercontent.com/2820709/105698302-01d34e80-5f06-11eb-868b-a9da30290a60.png)

**Comment by emiltin** [comment]
ah, thanks

**Comment by otterdahl** [comment]
Perhaps it's a better idea to simply print the log to the default output insead, so it shows up under "test" or "log instead

**Comment by emiltin** [comment]
hmm not sure. maybe for now it's better that it's separate files

**Comment by otterdahl** [comment]
The EC2 runner is working and we can establish a RSMP connection. However, we are unable to get any real data from it, so I suspect that the configuration of TLC is not complete.

**Comment by otterdahl** [comment]
> It would to great to run tests against the ruby TLC as well

That is a good idea. I suspect that it needs to run `bundle exec rsmp site --type tlc --json --config config/ruby.yaml` and while it is at the same time run `rspec spec/site`?

Is the ruby.yaml the correct config file? I get the follow error `TLC must have a main component (RSMP::ConfigurationError)`

**Comment by emiltin** [comment]
you need to use:
```
bundle exec rsmp site --type tlc --json --config config/tlc.yaml
```

**Comment by emiltin** [comment]
Yes you run rsmp site (maybe outputting to a file) and keep it running, then run rspec.

**Comment by emiltin** [comment]
You can use & to run it in the background, see e.g. https://linuxize.com/post/how-to-run-linux-commands-in-background/

**Comment by otterdahl** [comment]
OK. I've made a first try: d4a0301c14916622b8ab0316e73a96294580665c

**Comment by otterdahl** [comment]
The test against the ruby TLC works, with the exception of the alarm test

```
Failures:

  1) RSMP site alarm A0302 detector error (logic error)
     Failure/Error: raise "Aborting test because script config is missing" unless SCRIPT_PATHS
     
     RuntimeError:
       Aborting test because script config is missing
```

Is there any way to simulate an alarm with the ruby TLC? Or should we skip the test for the ruby TLC?

**Comment by emiltin** [comment]
There is currently no way to trigger alarms in the ruby tlc, so we should skip test that require scripts. They are already tagged with 'script' to make this easy (because i'm skipping them when running test locally against the ruby tlc):

```
bundle exec rspec --tag '~script' spec/site
```

**Comment by emiltin** [comment]
when looking at a PR, two checks are shown for each type of equipment, but one seem to be just the upload of log files?

**Comment by otterdahl** [comment]
> when looking at a PR, two checks are shown for each type of equipment, but one seem to be just the upload of log files?

Yes. They are run as different jobs, where the "test" job needs to finish before the "log" job can start. The reason I made it this way was because if the first step fails, then "upload log" won't be run. So simply split them into different jobs in the workflow.  I believe this can be fixed using the "if" conditional in each step. I'll try to fix this.

**Comment by otterdahl** [comment]
Since CI is set up and working. I think we can close this issue.
