### ISSUE TITLE
Add time synchronization test

### ISSUE THREAD

**Issue by sweco-seguro** [rsmp-nordic/rsmp_validator#60]
Test time synchronization.

Set time in the supervisor.
Wait.
Verify that time is set.

**Comment by sweco-seguro** [comment]
@emiltin In the manual testing protocol the time is changed and then the change is verified by checking the watchdog messages.

Do you think there’s any special reason it has to be done via watchdog messages or could status S0096 (current date and time) be used just as well?

**Comment by emiltin** [comment]
I think S0096 could be used just as well. And it's probably easier, since there are helper methods in the rsmp gem specifically for waiting for a status message. You can also wait for a watchdog, but it's a bit more low-level, as you need to use a Collector object.

**Comment by otterdahl** [comment]
I think there is a point in testing both time synchronization with watchdog messages as well as using M0104 & S0096.

Historically we have observed bugs in a TLC where M0104 would set the clock one hour off, while sync using watchdog messages worked fine.

**Comment by emiltin** [comment]
done
