### ISSUE TITLE
test timestamps when using M0104

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#70]
I added support in the ruby tlc for M0104, setting the clock. But I noticed that messages like AggregatedStatus and CommandResponse includes a timestamp that is still using the system clock. But we don't yet test these timestamps, we only check what S0096 returns.

_Originally posted by @emiltin in https://github.com/rsmp-nordic/rsmp_validator/issues/69#issuecomment-772439933_

**Comment by emiltin** [comment]
Theses messages include timestamps:

- AggregatedStatus
- Alarm
- StatusResponse
- CommandResponse
- Watchdog

**Comment by GunnarRolander** [comment]
I'll take a look at this.

**Comment by GunnarRolander** [comment]
In the pull request it checks StatusRequests, should we make tests to check the rest of the message types?

**Comment by emiltin** [comment]
yes. you might even want to move the statusresponse timestamp check to a separate test

**Comment by sweco-seguro** [comment]
Should I maybe create a new test file even? Seeing as we're sending commands, statusRequests, and probably will be triggering alarms too. Or do we still consider it a test of M0104 and should keep it in command_spec?

Btw, is there any way to request an aggregated status? I can't seem to find any.

**Comment by otterdahl** [comment]
> Btw, is there any way to request an aggregated status? I can't seem to find any.

It's only possible with RSMP 3.1.5, see [Aggregated status request message](https://rsmp-nordic.github.io/rsmp_core/applicability/basic_structure.html#aggregated-status-request-message)

**Comment by emiltin** [comment]
There is no support yet, but we should add that. Tracking in https://github.com/rsmp-nordic/rsmp/issues/18

**Comment by emiltin** [comment]
I suggest adding a new file spec/site/clock_spec.rb for all the tests related to m0104 and s0096.
We're planning a reorganization anyways, see #22

**Comment by emiltin** [comment]
Support for aggregated status request has been added in the gem, and there's a test in aggreated_status_request_spec.rb that tests it's use. Note that the test is tagged with rsmp>=3.1.5, meaning it will be filtered out unless the config for the tested equipment meets this criteria, see config/ci/rsmp_gem.yaml for an example. EC-2 and ITC-2 of course does not yet support 3.1.5 or aggregated status request.

**Comment by emiltin** [comment]
done
