### ISSUE TITLE
consider moving github actions to rsmp_implementations

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#73]
The github actions that run tests against real equipment would perhaps fit better in the rsmp_implementations repo.

The benefit would be that we could use testing in the rsmp_validator repo to validate the code of the rsmp_validator itself (by running tests against the rsmp gem), and expect all tests to pass. Currently this is mixed with testing of equipment, which is why we always see test failing since there are bugs in the equipment.

It would also allow us to remove stuff related to our specific test setup from the rsmp_validator repo. This would be preferable, as we want other people to use the validator.

The rsmp_implementations repo would also be a more natural place to show the results of testing equipment.

**Comment by otterdahl** [comment]
It makes sense. I'll try to add the real equipment to the rsmp_implementations instead, as soon as we get them up and running.

**Comment by otterdahl** [comment]
There a several questions that needs answers before we can move the github actions:

- The workflows is located at .github/workflows, but the config for rsmp_validator is located config/ci/. Should the CI specific configs be moved as well?
- The actions assumes that the current repo is to be checked out. Is it possible to check out a different repo? Do we need to check out multiple repos if the config file is elsewhere? or should the config file be integrated into the workflow file?
- The workflow dispatchers on push or pull_request isn't used, since no code exists in rsmp_implementations. The CI runners is only triggered manually

**Comment by emiltin** [comment]
Yes, we should to consider if it's a good idea or not.

Things in config/ci related to equipment would move. But the files for the ruby gem would stay (or be copied, since we might also want to use in in the implementations repo).

Regarding repo checkout, I imagine we would include the validator repo either as a gem or a git submodule. so when you check out the implemations repo, you get the validator repo as well. This would be similar to how other people would use the validator.

I havent' worked with GitHub actions, but this post suggest there are ways to trigger actions between repos:
https://github.community/t/triggering-by-other-repository/16163

**Comment by emiltin** [comment]
> The workflows is located at .github/workflows, but the config for rsmp_validator is located config/ci/. Should the CI specific configs be moved as well?

yes. and we should remove the folder config/ci from the validator repo.

> The actions assumes that the current repo is to be checked out. Is it possible to check out a different repo? Do we need to check out multiple repos if the config file is elsewhere? or should the config file be integrated into the workflow file?

i think the config should be in the rsmp_implementations repo. we would then check out the rsmp_validator repo. that's quite easy to do with a git shallow clone.

> The workflow dispatchers on push or pull_request isn't used, since no code exists in rsmp_implementations. The CI runners is only triggered manually

it should be posssible to trigger workflows in repo B when there's a push to repo A: https://blog.marcnuri.com/triggering-github-actions-across-different-repositories/.

btw, we should consider additionally running checks on a schedule, (e.g. once per day) so that if anything changes in the equipment, we get fresh test results automatically

**Comment by otterdahl** [comment]
I've opened a pull request here: https://github.com/rsmp-nordic/rsmp_implementations/pull/12

**Comment by otterdahl** [comment]
The equipment tests are now moved to rsmp_implementations. And changes in rsmp_validator should trigger the workflows.

**Comment by otterdahl** [comment]
I think this is working now, so I'm closing this issue
