### ISSUE TITLE
Add test: Check that the site disconnects when not responding to Watchdog

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#8]
Suggestion of test:

It would be useful to add a test checking that the site actually disconnects when not recieving MessageAck for a watchdog message.

Two scenarios:
- Missing MessageAck during handshake procedure
- Missing MessageAck after successful handshake

**Comment by emiltin** [comment]
Testing this would require knowing the ack timeout of the site.

**Comment by emiltin** [comment]
Implemented in https://github.com/rsmp-nordic/rsmp_validator/blob/master/spec/site/disconnect.rb.
The tests will wait for 10 seconds for the site to disconnect. This should probably be configurable.

**Comment by emiltin** [comment]
There's also currently an issue with later test ending up with a modified Site Proxy object.

**Comment by emiltin** [comment]
Fixed the issue with modofied objects been reused.

**Comment by emiltin** [comment]
Incorrect behaviour during connect is not implemented yet.

**Comment by emiltin** [comment]
done
