### ISSUE TITLE
Config file for setting componentIds

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#9]
Each piece of equipment tested might have different componentIs, etc. This should be read from a config file, so it's easy to adjust.

**Comment by otterdahl** [comment]
In order to write tests for some statues such as S0201, where the component is a **signal group** and not **traffic controller** (main component), I've added them to the config file:

```
      components:
        :any:
          traffic_controller: 'KK+AG9998=001TC000'
          signal_group_prefix: 'KK+AG9998=001SG'
          detector_logic_prefix: 'KK+AG9998=001DL'
```

I realize that this format is not consistent with other parts of the code. This is something we need to improve

**Comment by emiltin** [comment]
Test fails if the config has not been updated. The code should check that valid configs are present:
```
 0.27s    error: #<Async::Task:0x10f4 (failed)> [pid=1565] [2020-03-16 13:28:24 +0100]
               |   NoMethodError: undefined method `+' for nil:NilClass
               |   → /Users/emiltin/Documents/code/rsmp_validator/spec/site/alarm_spec.rb:5 in `block (3 levels) in <top (required)>'
               |     /Users/emiltin/Documents/code/rsmp_validator/spec/support/test_site.rb:79 in `block in connected'
               |     /Users/emiltin/Documents/code/rsmp_validator/spec/support/test_site.rb:24 in `block in within_reactor'
               |     /Users/emiltin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/async-1.23.0/lib/async/task.rb:255 in `block in make_fiber'
```

**Comment by emiltin** [comment]
The revised config is passed to RSMP::Supervisor.new. Since it expect a different format, the proxy site components are initialized incorrectly with incorrect ids.

The expected format is what's used in the config files in the rsmp gem:
```yaml
components:
  TC:
    type: main
    cycle_time: 6
  A1:
    type: signal_group
    plan: '11NBBB'
  A2:
    type: signal_group
    plan: '1NBBBB'
```

The reason for the change was a need to provide a signal group and detector_logic component id for use in tests?

**Comment by otterdahl** [comment]
Yes. I needed some way to provide signal group and detector logic in order to continue writing test cases. I didn't check the rsmp gem beforehand. Feel free to update the format for consistency.

**Comment by emiltin** [comment]
What's the use case for a prefix, rather than simply a component? Can we simply provide a few components, rarther than just one? Eg:

TC - main traffic controller component
KK+AG9998=001SG - signal group 1
KK+AG9998=002SG - signal group 2

**Comment by otterdahl** [comment]
There is a use case if a status test needs to test many components in the same test. For instance, when testing traffic counting for each detector logic (S0201).

But using prefixes assumes the use of components specific for the TLC SXL. I guess it is possible to simply provide components instead. But it could mean that we need to provide very many components in the config file if we'd like to test all detector logics and signal groups. But that may not be such a big problem. What do you think?

**Comment by emiltin** [comment]
Using a prefix does not tell you how many components exists in the device? In any case, if we want to test all components, the user will have to adjust a config to reflect the equipment being tested, since there is no way (yet) to fetch the list of components.

**Comment by otterdahl** [comment]
> Using a prefix does not tell you how many components exists in the device?

True. We still need to provide the number of components somehow in order for the prefixes to make sense.

> In any case, if we want to test all components, the user will have to adjust a config to reflect the equipment being tested, since there is no way (yet) to fetch the list of components.

Yes. The user still needs to adjust the config file anyway

**Comment by emiltin** [comment]
In that case I think it's simpler to just provide the list of components? Eg:
```yaml
components:
  main:
    KK+AG9998=001TC000:
  signal_group:
    KK+AG9998=001SG001:
    KK+AG9998=001SG002:
    KK+AG9998=001SG003:
    KK+AG9998=001SG004:
  detector_logic:
    KK+AG9998=001DL001:
    KK+AG9998=001DL002:
    KK+AG9998=001DL003:
    KK+AG9998=001DL004:
```

Signal groups could potentially have names that doesn't include couting, like:

```yaml
components:
  main:
    TC:
  signal_group:
    A1:
    A2:
    B1:
    B2:
```

This might be how we might name component in the Ruby TLC.

**Comment by emiltin** [comment]
Fixed
