### ISSUE TITLE
Some workflow fails to run

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#96]
The Dynniq EC2 github action workflow has been queued for two hours without running.

**Comment by otterdahl** [comment]
I've contacted Dynniq about this

**Comment by otterdahl** [comment]
Should be fixed now

**Comment by otterdahl** [comment]
Now there is some strange issue setting up ruby on windows...

**Comment by emiltin** [comment]
it seems to hang after downloading.
did you see this note about using ruby/setup-ruby@v1?
https://github.com/ruby/setup-ruby#using-self-hosted-runners

**Comment by otterdahl** [comment]
Thanks for the tip. Clearing C:/hostedtoolcache seems to fix the issue
